Docker compose down added to startup routine for VSC Dev Container
OpenEnergyDashboard/OED pull request #1228
Opened 2024-05-07 05:04 UTC by AdityaMSaraf

# Description

Added a docker compose down command to the VSC Dev Container startup process to prevent VSCode from crashing when an dev container instance is already running.

Fixes #[issue] (No Issue # found)

## Type of change

- [ ] Note merging this changes the database configuration.
- [ ] This change requires a documentation update

## Checklist

- [x] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [x] I have removed text in ( ) from the issue request
- [x] You acknowledge that every person contributing to this work has signed the [OED Contributing License Agreement](https://openenergydashboard.github.io/developer/cla.html) and each author is listed in the Description section.

## Limitations

None found yet, although this issue could still persist under different circumstances.

2024-05-08 13:29 UTC, huss requested changes
Thanks to @AdityaMSaraf for this work. I made a comment on the comment but that is minor. In the bigger picture, I'm still having issues with restarting the OED in VSC.

- I cloned a clean version and it started fine in the VSC container.
- I closed the remote connection and then reopened it. This did not work. The date on the Docker containers did not change. I tried closing VSC and redoing along with opening in WSL and then opening in container but the result was the same. The nohup.out file finishes with

> [6626 ms] Start: Run in container: mkdir -p '/root/.devcontainer' && CONTENT="$(cat '/root/.devcontainer/.updateContentCommandMarker' 2>/dev/null || echo ENOENT)" && [ "${CONTENT:-2024-05-08T13:03:36.001052436Z}" != '2024-05-08T13:03:36.001052436Z' ] && echo '2024-05-08T13:03:36.001052436Z' > '/root/.devcontainer/.updateContentCommandMarker'
> [6632 ms] 
> [6632 ms] 
> [6632 ms] Exit code 1
> [6632 ms] Start: Run in container: mkdir -p '/root/.devcontainer' && CONTENT="$(cat '/root/.devcontainer/.postCreateCommandMarker' 2>/dev/null || echo ENOENT)" && [ "${CONTENT:-2024-05-08T13:03:36.001052436Z}" != '2024-05-08T13:03:36.001052436Z' ] && echo '2024-05-08T13:03:36.001052436Z' > '/root/.devcontainer/.postCreateCommandMarker'
> [6638 ms] 
> [6638 ms] 
> [6638 ms] Exit code 1
> [6673 ms] Start: Run in container: # Test for /root/.gitconfig and git
> [6680 ms] [user]
> [credential]
> /root/.gitconfig exists
> [6680 ms] 
> [6680 ms] Exit code 1
> [6687 ms] Start: Run in container: # Cleaning up git config
> [6699 ms] 
> [6699 ms] 
> [6699 ms] Start: Run in container: command -v git >/dev/null 2>&1 && git config --global --replace-all credential.helper '!f() { /root/.vscode-server/bin/b58957e67ee1e712cebf466b995adf4c5307b2bd/node /tmp/vscode-remote-containers-ad53aa67-3e0d-4873-83b8-c74fec5ab1b0.js git-credential-helper $*; }; f' || true
> [6706 ms] 
> [6707 ms] 
> [7175 ms] Port forwarding connection from 63336 > 45903 > 45903 in the container.
> [7175 ms] Start: Run in Host: docker exec -i -u root -e VSCODE_REMOTE_CONTAINERS_SESSION=931f27cf-6035-4001-8841-732d7e199e4c1715173541821 c052d5d27f8dcf7c5fbd293b5acc49b3f8b40ddee6fab890542c62d39e895506 /root/.vscode-server/bin/b58957e67ee1e712cebf466b995adf4c5307b2bd/node -e 
> [7369 ms] Port forwarding connection from 63338 > 45903 > 45903 in the container.
> [7375 ms] Start: Run in Host: docker exec -i -u root -e VSCODE_REMOTE_CONTAINERS_SESSION=931f27cf-6035-4001-8841-732d7e199e4c1715173541821 c052d5d27f8dcf7c5fbd293b5acc49b3f8b40ddee6fab890542c62d39e895506 /root/.vscode-server/bin/b58957e67ee1e712cebf466b995adf4c5307b2bd/node -e 
> [7433 ms] Port forwarding 63336 > 45903 > 45903 stderr: Connection established
> [7596 ms] Port forwarding 63338 > 45903 > 45903 stderr: Connection established
> [12478 ms] Port forwarding 63336 > 45903 > 45903 stderr: Remote close
> [12520 ms] Port forwarding 63336 > 45903 > 45903 terminated with code 0 and signal null.
> [12611 ms] Port forwarding 63338 > 45903 > 45903 stderr: Remote close
> [12646 ms] Port forwarding 63338 > 45903 > 45903 terminated with code 0 and signal null.
> [132537 ms] Port forwarding 63336 > 45903 > 45903: Local close with error
> [132663 ms] Port forwarding 63338 > 45903 > 45903: Local close with error

There last two lines show up after a little while.

- I then reopened in WSL (outside VSC container) and did ``docker compose up`` in a terminal. This failed but after doing a ``docker compose down`` it started fine. I shut down OED and retried the container but it failed as before. Closing remote and opening in WSL with ``docker compose up`` worked fine where the Docker container dates did not change.
- I stopped OED, did ``docker compose down``, reopened in container and it worked fine in VSC. Thus, it seems manually doing the  ``docker compose down`` before restarting in VSC container works.

Did you see this behavior? If so, then it may be the case that the  ``docker compose down`` has to happen at the start and not after the VSC container is started and before the OED install after that as is done in this PR. If not, we need to try to determine why I see something different.

2024-05-08 13:29 UTC, huss commented on .devcontainer/devcontainer.json
> +	// When you use the command below then the output goes into nohup.out. The docker compose down is run to prevent vscode from crashing at startup.
A few thoughts:

- OED prefers lines to be 150 characters or less with 100 or so as desired. Thus, please split this comment so each sentence is on a separate line.
- cra\ashes has issue.
- behaviour has spelling issue.
- Please add this sentence at end of comment:
This may also address other issues seen and is low cost so seems a good idea.

2024-05-08 19:41 UTC, AdityaMSaraf commented
I am unsure why it is not working on your end, but VSCode also has tasks that can run at startup as opposed to only when the dev container restarts, I can try implementing that by EOD and that might be a better solution for this overall.

2024-07-16 19:31 UTC, huss commented
This has not moved so I created issue #1308  to address this. Thus, I am closing this PR.

2024-07-16 19:31 UTC, closed without merging