Issue 1182 date range & 1165 dates used by calendar
OpenEnergyDashboard/OED pull request #1318
Opened 2024-07-24 06:53 UTC by williamw04

# Description

In graphs, such as line, bar and radar, final dates within the date range are not displayed. This is issue since intuitively users would expect data from the entire range of dates including the last date. This was unintentionally caused by OED's decision to only display full days. This behavior stems from the decision that displaying partial dates was undesirable for graphs such as bar and 3D. Given an end date, OED would cut the rest of the date i.e. given a date at 11:00:00 OED would truncate this date to 00:00:00 of the current date. 

To address this issue, the date is first taken from the redux state then manipulated pushing the end date forward by a millisecond. This would roll the end date to the beginning of the next day providing the correct range when fetching data. However, we want to display the proper date range in the OED web application so that action should be reversed. 

This was implemented in the dateRangeToTimeInterval method in which the end date was pushed forward and timeIntervalToDateRange when that action was reversed. 

In the DateRangeComponent, when a date interval was selected, handleChange would call dispatch to update the TimeInterval using the dateRangeToTimeInterval method. The dateRangeToTimeInterval method reformats the date range to the international standard for time before being converted to a moment object. The dispatch action changes the state, and redux & react would realize that the changed is directly related to timeinterval which causes the site to be repainted. This was result in value being updated, in which timeIntervalToDateRange(queryTimeInterval) would be called and would reverse the added millisecond.

Fixes #1182 & Fixes #1165

## Type of change

- [ ] Note merging this changes the database configuration.
- [ ] This change requires a documentation update

## Checklist

- [ X ] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [ X ] I have removed text in ( ) from the issue request
- [ X ] You acknowledge that every person contributing to this work has signed the [OED Contributing License Agreement](https://openenergydashboard.github.io/developer/cla.html) and each author is listed in the Description section.

## Limitations

The case when the user selects a partial date by using the slider the last date might not be displayed. This is caused when there are no points of data available before the end time on the end date. This is due to the unit/frequency of the data points returned by the server. I.e when you move a slider to 10:51:00 and the server is returns data at noon 12:00:00 of every date, the data point of 12:00:00 of the end date is out of range and not graphed. As a result the last point it graphs it 12:00:00 of the previous date. 

Another issue found, is bar graph is unable to display data for a singular date.

2024-07-24 13:20 UTC, huss commented
I'm leaving a note that when you use the slider to select the dates and the graphic shows whole days then the date range picker may be one day earlier at start and/or one day later at end. This is because any partial days are not used (except 3D) but they are shown on the date range picker. This is not a bug but the way OED works. The documentation should be updated for this.

2024-07-24 13:26 UTC, huss requested changes
Thanks to @williamw04 for finding a clean solution to issue #1182. I have a few minor comments to address. Also, I tried using one day per issue #1165 and found that bar still does not show any data. I suspect the reason is separate from the change so far. If you agree either fix the issue or remove that issue from this PR.

2024-07-24 13:26 UTC, huss commented on src/client/app/components/BarChartComponent.tsx
I think the blank line and console log should be removed.

2024-07-24 13:26 UTC, huss commented on src/client/app/redux/selectors/chartQuerySelectors.ts
> +
Please remove the new blank line.

2024-07-24 13:26 UTC, huss commented on src/client/app/utils/dateRangeCompatibility.ts
> +		7.20.2020 at 00:00:00. This is due to OED decision to graph only entire days causing the lost of the last date.
I think 7.20 -> 7.22. Also, if you want to use the standard representation that the code uses then it is 2020-07-22 23:59:59 (as example).

2024-07-25 20:44 UTC, williamw04 commented
Added add changes and addressed issue #1165

2024-07-26 17:53 UTC, huss approved these changes

2024-07-26 18:06 UTC, merged