Default meter select
OpenEnergyDashboard/OED pull request #1348
Opened 2024-09-30 04:36 UTC by nneni

# Description

Fixes #1186 

Utilized React's useEffect hook to manage which option is selected when there is only one option (the only available choice, by default). 

## Type of change

- [ x] Note merging this changes the database configuration.
- [ ] This change requires a documentation update

## Checklist

- [ x] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [ x] I have removed text in ( ) from the issue request
- [ x] You acknowledge that every person contributing to this work has signed the [OED Contributing License Agreement](https://openenergydashboard.github.io/developer/cla.html) and each author is listed in the Description section.

## Limitations

None, at first the code was too specific and only applied to one of the data categories but after reanalysis it was rewritten to work in a more general sense.

2024-10-01 21:55 UTC, mmehta2669 commented
The code looks good, and very clear wit the functionality. it works and I'm personally not familiar with the nuances of react to determine if there is a better solution.

2024-10-02 00:04 UTC, Rakesh-Ranga-Buram commented
Everything looks good to me. Please convert this graph to PR.

2024-10-03 14:30 UTC, huss commented
This is a note to be sure that PR #1314 does similar logic/effect or to get them in sync. This does not directly impact this PR.

2024-10-03 14:34 UTC, huss requested changes
Thanks to @nneni for another contribution. Review found it works as expected. I have made a couple of small comments to address.

2024-10-03 14:34 UTC, huss commented on src/client/app/components/ThreeDPillComponent.tsx
Please remove extra blank line.

2024-10-03 14:34 UTC, huss commented on src/client/app/components/ThreeDPillComponent.tsx
> +	}, [meterPillData, groupPillData, dispatch]);
I'm unsure why this depends on dispatch. Removing that dependency did not impact the code when I tired it.

2024-10-05 19:46 UTC, nneni commented
Thanks for catching those! Just made the edits and pushed them.

2024-10-06 16:33 UTC, huss approved these changes
Thanks to @nneni for addressing the comments. Review and testing found it addressed them all correctly. Congratulations on another accepted contribution.

2024-10-06 16:33 UTC, merged