Added test BG14
OpenEnergyDashboard/OED pull request #1352
Opened 2024-10-03 18:08 UTC by Emily-D-2003

# Description

Added tests BG14 from design document.

Partly addresses #962 

## Type of change

- [ ] Note merging this changes the database configuration.
- [ ] This change requires a documentation update

## Checklist

(Note what you have done by placing an "x" instead of the space in the [ ] so it becomes [x]. It is hoped you do all of them.)

- [x] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [x] I have removed text in ( ) from the issue request
- [x] You acknowledge that every person contributing to this work has signed the [OED Contributing License Agreement](https://openenergydashboard.github.io/developer/cla.html) and each author is listed in the Description section.

2024-10-03 18:51 UTC, huss requested changes
Thanks to @Emily-D-2003 for their first pull request. First, my records do not indicate you signed the CLA. OED cannot accept your contribution without that. Second, I have made several comments to consider. I believe this is why the GitHub test failed for the new test case (it also failed locally on my machine).

2024-10-03 18:51 UTC, huss commented on src/server/test/web/readingsBarGroupQuantity.js
> +                    const expected = await parseExpectedCsv('src/server/test/web/readingsData/expected_bar_group_ri_15-20_mu_kWh_gu_lbsCO2_st_-inf_et_inf_bd_1.csv');
The expected file needs to be downloaded from the Dev Docs and added in the appropriate place in the repository. Direction are here: https://github.com/OpenEnergyDashboard/DesignDocs/blob/main/testing/testing.md#documentation-on-how-testing-data-is-created-and-used.

2024-10-03 18:51 UTC, huss commented on src/server/test/web/readingsBarGroupQuantity.js
> +                    //loads data into database
The description lists these units/conversions: u2, u10, u11, u12, u13, c11, c12, c13, c14. All but u2 need to be included in the test. Test B14 uses the same units and is completed.

2024-10-03 18:51 UTC, huss commented on src/server/test/web/readingsBarGroupQuantity.js
> +                    //load data from mcsv file
mcsv -> csv.

2024-10-20 14:14 UTC, huss commented
@Emily-D-2003 Do you need any help with this pull request? I was checking the status of the pull requests and wondered about this one.

2024-10-24 03:43 UTC, Emily-D-2003 commented
> @Emily-D-2003 Do you need any help with this pull request? I was checking the status of the pull requests and wondered about this one.

Thank you for the detailed comments and for checking in about the status of this PR! **Just committed the updates made according to your comments.**

One question - when attempting to sign the [CLA](https://openenergydashboard.org/developer/cla.html), the webpage linked in the README returned a HTTP 404. Wondering if you're seeing the same?

Thanks!

2024-10-24 15:49 UTC, huss commented
> One question - when attempting to sign the [CLA](https://openenergydashboard.org/developer/cla.html), the webpage linked in the README returned a HTTP 404. Wondering if you're seeing the same?

Someone else just reported this and has a PR in to fix it in one place and I'll do the others. The correct link is https://openenergydashboard.org/developer/cla/. Thanks for asking.

2024-10-24 18:30 UTC, huss commented
There is some issue that I have not yet figured out. I plan to work more on this later. FYI for @Emily-D-2003 .

2024-10-24 22:08 UTC, huss requested changes
Thanks to @Emily-D-2003 for their changes. They addressed the comments already made but another item has now appeared. Please see my comment for details and options to address this. Note that testing the code locally (directions on the design docs test page) may help with working on this if you do that. Once that is addressed and the CLA is done then this should be fine.

2024-10-24 22:08 UTC, huss commented on src/server/test/web/readingsBarGroupQuantity.js
> +                    await prepareTest(unitDatakWh, conversionDatakWh, meterDatakWhGroups, groupDatakWh);
The issue is that the provided meters and groups have a default graphic unit of kWh but this test does not create that unit. This causes the code to fail. What needs to happen is the needed meters and groups must be created within this test. It is similar to the standard ones but modified somewhat. I created the needed code to test the solution. If you want that code or for me to commit/push the solution then let me know.

2024-12-01 14:06 UTC, huss commented
@Emily-D-2003 It has been over a month since the last comments where made on this PR and no changes have been made. I plan to close this PR in one week (about 12/8) if the updates are not made or no comment is made to indicate this is active.

2024-12-06 02:36 UTC, Emily-D-2003 commented
> @Emily-D-2003 It has been over a month since the last comments where made on this PR and no changes have been made. I plan to close this PR in one week (about 12/8) if the updates are not made or no comment is made to indicate this is active.

@huss Apologies for the delay! These comments slipped through somehow. On it, aiming to push the updates in a week. Thanks!

2025-01-20 15:18 UTC, huss commented
> > @Emily-D-2003 It has been over a month since the last comments where made on this PR and no changes have been made. I plan to close this PR in one week (about 12/8) if the updates are not made or no comment is made to indicate this is active.
> 
> @huss Apologies for the delay! These comments slipped through somehow. On it, aiming to push the updates in a week. Thanks!

@Emily-D-2003 I hope all is well. It has been another month so I wanted to touch base on your plans. Will this get finished fairly soon or would it be better for someone else to move this forward?

2025-03-04 14:30 UTC, huss commented
> > > @Emily-D-2003 It has been over a month since the last comments where made on this PR and no changes have been made. I plan to close this PR in one week (about 12/8) if the updates are not made or no comment is made to indicate this is active.
> > 
> > 
> > @huss Apologies for the delay! These comments slipped through somehow. On it, aiming to push the updates in a week. Thanks!
> 
> @Emily-D-2003 I hope all is well. It has been another month so I wanted to touch base on your plans. Will this get finished fairly soon or would it be better for someone else to move this forward?

@Emily-D-2003 I hope you are well. OED appreciates your efforts on this work. This PR has been sitting for a while. To either complete this work or allow another student to do this test, I'll give you until March 15, 2025 to complete this work. After that date I will close this PR if it is not complete and make the test case available to someone else. You can comment here or message me on Discord (see contact info on our website) if you wish to discuss this.

2025-03-16 16:09 UTC, huss commented
This PR is now considered stale and is being closed. The task is being made available to others. If @Emily-D-2003 wishes to pursue this work then they should ask again if it is available before proceeding.

2025-03-16 16:09 UTC, closed without merging