Adding negative function to maps
OpenEnergyDashboard/OED pull request #1357
Opened 2024-10-05 01:53 UTC by mmehta2669

# Description

Added changes to maps to handle negative values

Fixes #1205 

## Type of change

(Check the ones that apply by placing an "x" instead of the space in the [ ] so it becomes [x])

- [ ] Note merging this changes the database configuration.
- [ ] This change requires a documentation update

## Checklist

(Note what you have done by placing an "x" instead of the space in the [ ] so it becomes [x]. It is hoped you do all of them.)

- [ ] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [ ] I have removed text in ( ) from the issue request
- [ ] You acknowledge that every person contributing to this work has signed the [OED Contributing License Agreement](https://openenergydashboard.github.io/developer/cla.html) and each author is listed in the Description section.

## Limitations
N/A

2024-10-05 02:36 UTC, mmehta2669 commented
Thanks @huss for the suggestions on the code. All the suggestions were really helpful to understand how Plotly works.

2024-10-05 02:41 UTC, Rakesh-Ranga-Buram commented
Everything looks fine to me. Please convert this draft to PR

2024-10-06 16:21 UTC, huss requested changes
Thanks to @mmehta2669 for another contribution. Review and testing found it works as desired. I have made one small comment to address.

2024-10-06 16:21 UTC, huss commented on src/client/app/components/MapChartComponent.tsx
> +			// TODO DEBUG Using amp 1, 2 & 3 from test data that within map. This arbitrarily changes the value for testing.
Debugging statements that are commented out should be removed before the code is added to OED.

2024-10-08 13:06 UTC, huss approved these changes
Thanks to @mmehta2669 for addressing my comment. Everything looks good. Congratulations on another accepted contribution.

2024-10-08 13:06 UTC, merged