Added test case BG7
OpenEnergyDashboard/OED pull request #1380
Opened 2024-11-04 04:01 UTC by BigGeF

# Description
Added BG7 test case in readingsBarGroupQuantity.js
Added file expected_bar_group_ri_15-20_mu_kWh_gu_kWh_st_2022-08-20%07#25#35_et_2022-10-28%13#18#28_bd_13.csv

Mason Sain - @sainmas
Evan Thomas - @ethomas5
Pedro Valdovinos Reyes - @PValdovinos

Partly addresses [#692](https://github.com/OpenEnergyDashboard/OED/issues/962)

Fixes #[issue]

## Type of change

- [ ] Note merging this changes the database configuration.
- [ ] This change requires a documentation update

## Checklist

- [x] I have followed the [OED pull request](https://openenergydashboard.org/developer/pr/) ideas
- [x] I have removed text in ( ) from the issue request
- [x] You acknowledge that every person contributing to this work has signed the [OED Contributing License Agreement](https://openenergydashboard.org/developer/cla/) and each author is listed in the Description section.

## Limitations

2024-11-04 15:27 UTC, huss requested changes
Thanks to @BigGeF, @sainmas, @ethomas5 & @PValdovinos for their first contribution to OED. Testing and review found it works as expected. I did make a few comments that I would appreciate your response/action.

2024-11-04 15:27 UTC, huss commented on package-lock.json
> -		"node_modules/add-dom-event-listener": {
I'm curious why there is a change in a package associated with this PR. This PR relates to a test case so this seems outside its scope. Should it be here?

2024-11-04 15:27 UTC, huss commented on src/server/test/web/readingsBarGroupQuantity.js
> +                        const unitData = unitDatakWh;
I'm not sure it is best to reassign the name of the standard units & conversions to use them. The other test cases have not, as far as I know, done this. For these reasons, I would directly use the name and remove these two lines.

2024-11-04 15:27 UTC, huss commented on src/server/test/web/readingsBarGroupQuantity.js
> +
OED generally leaves at most one blank line between tests. Having two and containing spaces at the front is less desirable. Could you please remove them. There is also two empty blank lines after the test to remove.

2024-11-05 20:53 UTC, ethomas5 commented
@huss Not sure if resolving the changes pinged you on this, but just letting you know we got the PR comments addressed.

2024-11-05 21:20 UTC, huss approved these changes
Thanks to the team of @BigGeF, @sainmas, @ethomas5 & @PValdovinos for quickly addressing the comments. Review and testing found that all is in order. Congratulations on your first accepted contribution to OED.

2024-11-05 21:20 UTC, merged