Added testcase C5 to the file readingsCompareMeterQuantity
OpenEnergyDashboard/OED pull request #1397
Opened 2024-12-01 07:16 UTC by LauraV-702

# Description
Completed and added testcase C5 into the readingsCompareMeterQuantity.js file

Team:
@LauraV-702
@alstondsouza1
@Lizock
@Z1springer

Fixes testcase c5 from issue #[962]

## Type of change
- [ ] Note merging this changes the database configuration.
- [x] This change requires a documentation update

## Checklist
- [x] I have followed the [OED pull request](https://openenergydashboard.org/developer/pr/) ideas
- [x] I have removed text in ( ) from the issue request
- [x] You acknowledge that every person contributing to this work has signed the [OED Contributing License Agreement](https://openenergydashboard.org/developer/cla/) and each author is listed in the Description section.

## Limitations

2024-12-01 14:03 UTC, huss requested changes
Thanks to @LauraV-702, @alstondsouza1, @Lizock & @Z1springer for their first contribution to OED. Review and testing found it works as desired. I made two small comments about extra white space at the end of lines. I'm unsure why the OED checks did not catch this. Also, my records do not show the CLA being signed by @alstondsouza1, @Lizock & @Z1springer. Could you please do this via the link in the description or let me know that my records are off.

2024-12-01 14:03 UTC, huss commented on src/server/test/web/readingsCompareMeterQuantity.js
> +						curr_end: '2022-11-01 15:00:00',
This line has extra spaces at the end that need to be removed.

2024-12-01 14:03 UTC, huss commented on src/server/test/web/readingsCompareMeterQuantity.js
> +				  });
This line has extra tabs and spaces at the end that need to be removed.

2024-12-01 21:31 UTC, LauraV-702 commented
Hello, I've made changes as you directed, thank you! 
Hopefully these work this time. I've also notified my teammates to sign the CLA, I'll be sure to double check with them once more.

2024-12-01 23:22 UTC, huss commented
> Hello, I've made changes as you directed, thank you! Hopefully these work this time. I've also notified my teammates to sign the CLA, I'll be sure to double check with them once more.

@LauraV-702 It all looks good. One more CLA and this can be accepted. Thanks for addressing the comments.

2024-12-01 23:32 UTC, LauraV-702 commented
@huss Thanks for the confirmation! I've double checked with my team mates and now they've all signed the CLA!

2024-12-02 00:46 UTC, huss approved these changes
Everything looks good. Congratulations to @LauraV-702, @alstondsouza1, @Lizock & @Z1springer on your first accepted contribution to OED.

2024-12-02 00:46 UTC, merged

2024-12-02 00:48 UTC, LauraV-702 commented
Awesome, thank you!