Is valid gps input new
OpenEnergyDashboard/OED pull request #1402
Opened 2024-12-03 19:11 UTC by zhenga5

# Description

Changing IsValidGPSInput to include returning a message about why there is something invalid particularly involving GPS inputs whether the input lacks a comma, has too many commas, or the GPS coordinate is out of range.

## Type of change

(Check the ones that apply by placing an "x" instead of the space in the [ ] so it becomes [x])

- [ ] Note merging this changes the database configuration.
- [x] This change requires a documentation update

## Checklist

(Note what you have done by placing an "x" instead of the space in the [ ] so it becomes [x]. It is hoped you do all of them.)

- [x] I have followed the [OED pull request](https://openenergydashboard.org/developer/pr/) ideas
- [x] I have removed text in ( ) from the issue request
- [x] You acknowledge that every person contributing to this work has signed the [OED Contributing License Agreement](https://openenergydashboard.org/developer/cla/) and each author is listed in the Description section.

## Limitations

Shouldn't be any issues regarding IsValidGPSInput. It only changed the return type to {boolean, string}

2024-12-04 21:41 UTC, danielshid commented on src/client/app/utils/calibration.ts
>  		// TODO It would be nice to tell user that comma is missing but need to check all uses to be sure don't get ''.
Remove TODO comment.

2024-12-04 21:41 UTC, danielshid commented on src/client/app/utils/calibration.ts
> +			// TODO It would be nice to return the error and then notify as desired.
Remove TODO comment.

2024-12-04 21:54 UTC, danielshid commented
I noticed that the invalid GPS warnings appear only after the user saves the meter. The meter still stores the invalid GPS input. Unless Steve thinks otherwise, I think the warnings should appear as the user is editing the meter.

2024-12-04 22:01 UTC, danielshid commented
The pull request also still has text in ( ).

2024-12-04 22:05 UTC, huss commented
> I noticed that the invalid GPS warnings appear only after the user saves the meter. The meter still stores the invalid GPS input. Unless Steve thinks otherwise, I think the warnings should appear as the user is editing the meter.

The potential issue with checking in real time is that you will get errors while typing the GPS value. I think that is why we waited until the save is done. I think it is fine to leave it the way it is.

2024-12-06 00:11 UTC, huss commented on src/client/app/components/maps/MapCalibrationInfoDisplayComponent.tsx
> +		if (validGps) {
This isn't your doing but would it work if you had an else clause that showed the error if the GPS is invalid? Up to now the code simply does nothing.

2024-12-06 00:22 UTC, huss requested changes
Thanks to @zhenga5 for working on both of these TODO issues. Review and testing found it works fine and addressed the comments by @danielshid.

I cannot comment inside file without changes so here is a thought:

The isValidGPSInput in src/server/services/csvPipeline/uploadMeters.js is very similar to the modified one you changed in src/client/app/utils/calibration.ts. It was not your doing that there are two version but I think it would be good to remove the other one that is scoped to that file and use the modified one from your work.

I also made one other comment. Note both of these were not part of the original issue but related when I looked at the code. If you are willing to make these changes that would be very helpful. If not, then let me know and I can do them.

2024-12-06 00:23 UTC, huss commented
Note I pushed a commit to address formatting issues where most are outside the PR changes but in the same files.

2025-06-26 19:18 UTC, huss commented
> The isValidGPSInput in src/server/services/csvPipeline/uploadMeters.js is very similar to the modified one you changed in src/client/app/utils/calibration.ts. It was not your doing that there are two version but I think it would be good to remove the other one that is scoped to that file and use the modified one from your work.

I realized one was on the server so JS and not TS. Thus, I synchronized them and put in a TODO.

2025-06-26 19:43 UTC, huss commented
I addressed all the comments.

2025-06-26 19:44 UTC, huss approved these changes
All good now.

2025-06-26 19:44 UTC, merged