Issue #962, Test Case CG5
OpenEnergyDashboard/OED pull request #1411
Opened 2024-12-15 20:02 UTC by mRosenthal937

# Description

Wrote code for test case CG5 in the file readingsCompareGroupQuantity.js, allowing test case CG5 to successfully run.

Done as part of participating in a CTI program to allow developers to get some beginner-friendly open-source experience.

Worked with Kevin Beltran and Bo Liu as part of CTI. 

@mRosenthal937
@bo2020bo
@KevinBeltran23

Partly addresses issue #962 

## Type of change

- [ ] Note merging this changes the database configuration.
- [ ] This change requires a documentation update

## Checklist

- [X] I have followed the [OED pull request](https://openenergydashboard.org/developer/pr/) ideas
- [X] I have removed text in ( ) from the issue request
- [X] You acknowledge that every person contributing to this work has signed the [OED Contributing License Agreement] and each author is listed in the Description section.

## Limitations

No additional issues as known.

2024-12-17 13:42 UTC, huss commented
Thanks to @mRosenthal937, @bo2020bo & @KevinBeltran23 for this contribution to OED. The OED records do not indicate that any of you have signed the CLA. If this is correct, please use [this link](https://openenergydashboard.org/developer/cla/) to do this so the pull request can be reviewed. If you think this is incorrect then please let me know.

2024-12-23 06:46 UTC, KevinBeltran23 commented
Thank you @huss for notifying us.  
I believe everyone on our team has filled out the CLA by now. 
Please let us know if anything is still missing.

2024-12-23 15:42 UTC, huss requested changes
Thanks to @mRosenthal937, @bo2020bo & @KevinBeltran23 for their first contribution to OED. I'm sorry it took me this long to review as I was tied up. Review and testing found it works as expected. Congratulation on your first accepted contribution to OED.

2024-12-23 15:43 UTC, huss approved these changes

2024-12-23 15:43 UTC, merged