Issue #962, Test Case CG6
OpenEnergyDashboard/OED pull request #1412
Opened 2024-12-16 04:00 UTC by VanishedAIR

# Description

Finished writing code for test case CG6 in the file src\server\test\web\readingsCompareGroupQuantity.js, allowing test case CG6 to successfully run.

Done as part of participating in a CTI program to allow developers to get some beginner-friendly open-source experience.

Worked with Regina Huang and Andre Dargani as part of CTI.

Team members:
@VanishedAIR
@laurarian
@madargani

Partly addresses issue [#962](https://github.com/OpenEnergyDashboard/OED/issues/962)

## Type of change

- [ ] Note merging this changes the database configuration.
- [ ] This change requires a documentation update

## Checklist

- [x] I have followed the [OED pull request](https://openenergydashboard.org/developer/pr/) ideas
- [x] I have removed text in ( ) from the issue request
- [x] You acknowledge that every person contributing to this work has signed the [OED Contributing License Agreement](https://openenergydashboard.org/developer/cla/) and each author is listed in the Description section.

## Limitations

No additional issues as known.

2024-12-17 13:48 UTC, huss commented
Thanks to @VanishedAIR, @laurarian & @madargani for this contribution to OED. The OED records do not indicate that @laurarian has signed the CLA. If this is correct, please use the link in the Description Checklist to do this so the pull request can be reviewed. If you think this is incorrect then please let me know.

2024-12-17 18:18 UTC, laurarian commented
Hi,
I have signed the CLA now

Best,
Rong

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Steven Huss-Lederman ***@***.***>
发送时间: Tuesday, December 17, 2024 8:48:32 AM
收件人: OpenEnergyDashboard/OED ***@***.***>
抄送: Rong Huang ***@***.***>; Mention ***@***.***>
主题: Re: [OpenEnergyDashboard/OED] Issue #962, Test Case CG6 (PR #1412)


Thanks to @VanishedAIR<https://github.com/VanishedAIR>, @laurarian<https://github.com/laurarian> & @madargani<https://github.com/madargani> for this contribution to OED. The OED records do not indicate that @laurarian<https://github.com/laurarian> has signed the CLA. If this is correct, please use the link in the Description Checklist to do this so the pull request can be reviewed. If you think this is incorrect then please let me know.

―
Reply to this email directly, view it on GitHub<https://github.com/OpenEnergyDashboard/OED/pull/1412#issuecomment-2548510034>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ASWTAM45HSOQIJUQU3WJA6D2GATTBAVCNFSM6AAAAABTVIE2JKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNBYGUYTAMBTGQ>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-12-17 18:18 UTC, VanishedAIR commented
@huss I believe she just submitted just agreement right now, could you confirm you can see it on your end? Thanks!

2024-12-17 22:04 UTC, huss requested changes
Thanks to @VanishedAIR, @laurarian & @madargani for their first contribution to OED. Testing found it works as desired. I made two small comments to address. Also, the files ``docker-compose.yml``, ``package.json`` and ``package-lock.json`` are modified. Normally these would not be altered by adding a new test. Unless you have a reason for the change then these should be undone. I note that there is a new compile/build error that I'm hoping relates to this but I'll look again after the changes are made. Please let me know if you need anything.

2024-12-17 22:04 UTC, huss commented on src/server/test/web/readingsCompareGroupQuantity.js
>  				// Add CG6 here
Could you please remove the comment since CG6 is now done.

2024-12-17 22:04 UTC, huss commented on src/server/test/web/readingsCompareGroupQuantity.js
> +				mocha.it('CG6: 28-day shift end 2022-10-31 17:12:34 for 15-minute reading intervals and quantity units & kWh as kWh', async () => { //test description
The design doc seems to have slightly different text of " 28 day shift end 2022-10-31 17:12:34 (partial hour) for 15 minute reading intervals and quantity units & kWh as kWh". Could the text be updated?

2024-12-18 23:56 UTC, VanishedAIR commented
Would it be fine if for the docker-compose.yml, package.json and package-lock.json files I reverted back to the code that is present in the current OED files, because I think they changed when I pulled in some changes.

2024-12-19 00:21 UTC, huss commented
> Would it be fine if for the docker-compose.yml, package.json and package-lock.json files I reverted back to the code that is present in the current OED files, because I think they changed when I pulled in some changes.

@VanishedAIR Yes, that should be fine. I think the docker file was changed to allowed access to the Postgres DB. Why the others changed is unclear to me at this time.

2024-12-19 01:31 UTC, VanishedAIR commented
I copy and pasted from the current OED files, and commented the port back to its previous state, and updated the CG6 description. Let me know if anything else needs changes!

2024-12-23 16:45 UTC, huss commented
I am leaving a comment that I realized that the copy/paste that I said was okay changed the git history to show some previous changes in package.json as ones from this PR. I tried to fix but my git ability did not easily make it happen so I am letting it go. It also added some blank lines at the end of a few files. Overall, this is not too important but it will cause developers to have to do an npm install (happens automatically) after they pull this PR.

2024-12-23 16:59 UTC, huss requested changes
Thanks for updating the code and sorry it took me a few days to get back to this. Review and testing found it works as desired. Congratulations to @VanishedAIR, @laurarian & @madargani on your first accepted contribution to OED.

2024-12-23 16:59 UTC, huss approved these changes

2024-12-23 16:59 UTC, merged