UI-Testing
OpenEnergyDashboard/OED pull request #1417
Opened 2024-12-29 08:24 UTC by williamw04

# Description

The team @aravindb24 @shankarp05 and I were given the task to come up with a test strategy and to lay a foundation so that anyone interested can easily learn and gain hands on experience with UI-Testing. We produced a [UI Testing Documentation](https://github.com/williamw04/DesignDocs/blob/main/uiTesting/UITesting.md) to guide and address common issues.

We leveraged the framework Cypress to test UI and UX features. We used docker to containerize the testing environment so that results are consistent for everyone. 

There's still things that still need to be looked into such as testing redux state. For more information check the limitations section in the [UI Doc](https://github.com/williamw04/DesignDocs/blob/main/uiTesting/UITesting.md)

## Type of change

(Check the ones that apply by placing an "x" instead of the space in the [ ] so it becomes [x])

- [ ] Note merging this changes the database configuration.
- [x] This change requires a documentation update

## Checklist

- [x] I have followed the [OED pull request](https://openenergydashboard.org/developer/pr/) ideas
- [x] I have removed text in ( ) from the issue request
- [x] You acknowledge that every person contributing to this work has signed the [OED Contributing License Agreement](https://openenergydashboard.org/developer/cla/) and each author is listed in the Description section.

## Limitations

(Describe any issues that remain or work that should still be done.)

2025-01-09 19:22 UTC, huss requested changes
Thanks to @williamw04, @aravindb24 & @shankarp05 for this PR. I've made a few comments to consider but nothing substantial. One question is that when I tried to use this I got an error:
```
docker compose --profile ui-testing up
I got the error ``dependency failed to start: container oed-web-1 has no healthcheck configured``.
```
Does this happen for you? I wanted to try it and update the design doc with any changes for this PR so am curious how to get it to run properly.

2025-01-09 19:22 UTC, huss commented on .gitignore
> +#ui-testing screenshots
This folder is no longer present nor does OED normally have a folder for images in the code. Can this be removed or is it needed because the express.config.ts file puts screenshots there?

2025-01-09 19:22 UTC, huss commented on cypress.config.ts
> +
Extra spaces at start of the next two lines. Also, using spaces not tabs for indenting.

2025-01-09 19:22 UTC, huss commented on src/cypress/e2e/general_ui.cy.ts
> +describe('UI Functionality Tests for Open Energy Dashboard', () => {
It looks like the .ts files use spaces not tabs for indenting. Could it be changed (VSC can do this)?

2025-01-09 19:22 UTC, huss commented on src/cypress/e2e/initLangTest.cy.ts
> +
Extra blank line.

2025-01-09 19:22 UTC, huss commented on src/cypress/e2e/line.cy.ts
> +  // Graph Type is Line
This is the default case but the initial type of graphic can be changed on the admin settings page. Maybe add a comment that test should be enhanced?

2025-01-09 19:22 UTC, huss commented on src/cypress/e2e/line.cy.ts
> +  it('groups should be clickable and display 10 options and 1 incompatiable option', () => {
I think this assumes the default developer data is loaded without changes. Maybe worth noting.

2025-01-09 19:22 UTC, huss commented on src/cypress/e2e/line.cy.ts
> +		// Visit the OED application
This describe text is also used below. Should it be unique or something else?

2025-01-09 19:22 UTC, huss commented on src/cypress/e2e/test.cy.ts
> +	// it('should display the "Graph Type" button and toggle the dropdown', () => {
Since this is all commented out, what is it for?

2025-01-11 20:42 UTC, williamw04 commented
> Thanks to @williamw04, @aravindb24 & @shankarp05 for this PR. I've made a few comments to consider but nothing substantial. One question is that when I tried to use this I got an error:
> 
> ```
> docker compose --profile ui-testing up
> I got the error ``dependency failed to start: container oed-web-1 has no health check configured``.
> ```
> 
> Does this happen for you? I wanted to try it and update the design doc with any changes for this PR so am curious how to get it to run properly.

The error arises from there beingno health check defined in the web service. 

In the cypress service section, a "depends on web" is defined means the container depends/relies on the web to be running properly (have a healthy status so the healthcheck is the dependency that should have been started but was not sorry error). This is checked through health checks which was not previously defined. So moving forward if you were to define depend on you would have to have a defined health check in the service that is being depended upon.

Now with this being said the web service depends on the database so a health check must also be defined in the service.

2025-01-11 20:45 UTC, williamw04 commented on .gitignore
> +#ui-testing screenshots
So cypress will automatically put screenshots when there's an error in the test. This was configured to save to the path     screenshotsFolder: 'cypress/screenshots/e2e', within cypress.config.ts

I think that means if the folder isn't included within the development repo, it will automatically create one when needed so the folder and the images don't have to be included.

2025-01-11 20:45 UTC, williamw04 commented on cypress.config.ts
> +
Are we not suppose to use spaces for indenting?

2025-01-11 20:47 UTC, williamw04 commented on src/cypress/e2e/line.cy.ts
> +  it('groups should be clickable and display 10 options and 1 incompatiable option', () => {
That is true where do you think is best to note this down? Should is be apart of the main test?

2025-01-12 15:21 UTC, huss commented on .gitignore
> +#ui-testing screenshots
The cypress/ directory is not mapped from the container back to the developer's machine so it does not live there. However, I have sometimes seen it show up in VSC and the file system while the cypress container is running (not sure why). Thus, to avoid it ever showing up in git, I modified the directory in .gitignore to avoid seeing them.

2025-01-12 15:23 UTC, huss commented on cypress.config.ts
> +
I systematically converted the spaces to tabs. The developer first steps (https://openenergydashboard.org/developer/gettingStarted/#ide) does mention this. I also autoformatted in VSC to get rid of extra spaces.

2025-01-12 15:23 UTC, huss commented on src/cypress/e2e/general_ui.cy.ts
> +describe('UI Functionality Tests for Open Energy Dashboard', () => {
See other comment for my change.

2025-01-12 15:27 UTC, huss commented on src/cypress/e2e/line.cy.ts
> +  it('groups should be clickable and display 10 options and 1 incompatiable option', () => {
I added this to the design doc.

2025-01-12 15:33 UTC, huss commented on src/cypress/e2e/line.cy.ts
> +  // Graph Type is Line
I added a TODO about this.

2025-01-12 15:38 UTC, huss commented
> The issue is health checks would happen in running OED normally (docker compose up) which might be an undesired feature. The solution is to remove the health checks.

I've tried and so far there is no issue. My recollection is that in the past the database check did not actually verify that the DB could accept request and only that it is running. The install script tries to check/correct for this. I've made myself a action item to look into this more in the future but it seems fine unless someone finds an issue.

2025-01-12 15:41 UTC, huss commented
Thanks to @williamw04 for the updates. Given them and my changes it is looking good.

I do have an issue where several of the tests are failing. I've attached the terminal output. Do you ever see this? Any thoughts? I did try logging in as admin outside the testing (could only do if not running the special cypress startup) to see if that might be the cause but it did not seem to help.

[cyprusFailures.txt](https://github.com/user-attachments/files/18389991/cyprusFailures.txt)

2025-01-16 19:33 UTC, williamw04 commented on src/cypress/e2e/line.cy.ts
> +		// Visit the OED application
So the describe block is borrowed from Mocha's test infereceinterface. Describe explains the test within the block and can be used to describe different test within a file. So in the file I named it template spec since this test is a good test file for people to refer to when learning about testing with cypress.

2025-01-16 20:16 UTC, williamw04 commented
> Thanks to @williamw04 for the updates. Given them and my changes it is looking good.
> 
> I do have an issue where several of the tests are failing. I've attached the terminal output. Do you ever see this? Any thoughts? I did try logging in as admin outside the testing (could only do if not running the special cypress startup) to see if that might be the cause but it did not seem to help.
> 
> [cyprusFailures.txt](https://github.com/user-attachments/files/18389991/cyprusFailures.txt)

For the general_ui.cy aravind said he was unable to get most of his test working.
For the line.cy test i think it only passes if you install the test data.

2025-01-16 20:17 UTC, williamw04 commented
> > The issue is health checks would happen in running OED normally (docker compose up) which might be an undesired feature. The solution is to remove the health checks.
> 
> I've tried and so far there is no issue. My recollection is that in the past the database check did not actually verify that the DB could accept request and only that it is running. The install script tries to check/correct for this. I've made myself a action item to look into this more in the future but it seems fine unless someone finds an issue.

I wasn't aware that there was already a database check prior, so with this in mind we could remove all the health checks and depends on from the docker yml file

2025-01-23 18:25 UTC, huss commented
> > > The issue is health checks would happen in running OED normally (docker compose up) which might be an undesired feature. The solution is to remove the health checks.
> > 
> > 
> > I've tried and so far there is no issue. My recollection is that in the past the database check did not actually verify that the DB could accept request and only that it is running. The install script tries to check/correct for this. I've made myself a action item to look into this more in the future but it seems fine unless someone finds an issue.
> 
> I wasn't aware that there was already a database check prior, so with this in mind we could remove all the health checks and depends on from the docker yml file

We decided to leave the check. It may be possible to remove the loop in the install script but that is future work.

2025-01-23 18:26 UTC, huss commented
> > Thanks to @williamw04 for the updates. Given them and my changes it is looking good.
> > I do have an issue where several of the tests are failing. I've attached the terminal output. Do you ever see this? Any thoughts? I did try logging in as admin outside the testing (could only do if not running the special cypress startup) to see if that might be the cause but it did not seem to help.
> > [cyprusFailures.txt](https://github.com/user-attachments/files/18389991/cyprusFailures.txt)
> 
> For the general_ui.cy aravind said he was unable to get most of his test working. For the line.cy test i think it only passes if you install the test data.

I've added a TODO and info in the design document about needing a clean DB. I also commented out the tests that were failing and left the one that works.

2025-01-23 18:28 UTC, huss approved these changes
Thanks to @williamw04 for continuing to work on this and resolving the comments. It is now working as desired at this time.

2025-01-23 18:28 UTC, merged