Added descriptive error for duplicate name.
OpenEnergyDashboard/OED pull request #315
Opened 2018-03-07 20:00 UTC by jamielepito

Closes #135 
Changed the server to send 409 conflict error when a duplicate group name is detected and show a specific message on the client.

2018-03-07 21:38 UTC, NoraCodes approved these changes

2018-03-07 23:54 UTC, johndiiorio requested changes

2018-03-07 23:54 UTC, johndiiorio commented on src/server/routes/groups.js
> +				res.sendStatus(409); //409 conflict
I would not recommend using a 409 status code. Example from Wikipedia about 409 status codes: "conflict in the request, such as an edit conflict between multiple simultaneous updates."

I also recommend only using a limited number of status codes: 200, 400, 401, 403, 404, 429, and 500. Thus, I recommend that this should be a 400 - bad request.

2018-03-07 23:54 UTC, johndiiorio commented on src/client/app/actions/groups.ts
> +					showErrorNotification(`Name '${group.name}' was already taken.`);
For clarity, I would change this to "Group 'group name' is already in use."

2018-03-07 23:59 UTC, johndiiorio commented
I think that this PR should also extend to warning a user when editing the name of an existing group to a name that already exists.

2018-03-08 01:07 UTC, NoraCodes commented on src/server/routes/groups.js
> +				res.sendStatus(409); //409 conflict
> I also recommend only using a limited number of status codes

Why?

2018-03-08 03:26 UTC, johndiiorio commented on src/server/routes/groups.js
> +				res.sendStatus(409); //409 conflict
It is considered good practice by many companies. Google uses 9, Dropbox uses 10, Facebook uses 8 (I believe). A couple good articles: https://blogs.dropbox.com/developers/2015/04/how-many-http-status-codes-should-your-api-use/ and http://blog.restcase.com/rest-api-error-codes-101/

2018-05-07 01:59 UTC, sandeepacharya464 commented
@jamielepito  the code looks good. if you resolve the conflict, we can merge this in. :)

2018-10-25 04:04 UTC, johndiiorio approved these changes

2018-10-25 04:38 UTC, merged