Add robust meter diagnosis tools
OpenEnergyDashboard/OED pull request #329
Opened 2018-04-05 18:41 UTC by LeoTindall

These commits fix the updateMamacMeters error messages and add a script to check if meters are up, based on a CSV file of IPs (like ips.csv that we use for addMamacMeters).

2018-04-06 00:33 UTC, johndiiorio requested changes
Your checkMeters script is not integrated into the rest of the system. Ideally, it would email admins that meters are down. However, I think having a basic implementation is good for this pull request.

2018-04-06 00:33 UTC, johndiiorio commented on src/scripts/checkMeters.sh
> +		echo "	NO GOOD $success"
I think your message could be improved to `Meter failing with status $success`

2018-04-06 00:33 UTC, johndiiorio commented on src/scripts/checkMeters.sh
> +	curl -s -m 1 "http://$line" > /dev/null
It appears that the max timeout is 1 second. I think this should be increased to 5-10 seconds.

2018-04-06 00:41 UTC, jameeters approved these changes
All changes look good to me, although I'm unsure about adding the checkMeters script to the main repository. It seems like we should have a better place for ancillary tools like this, although I don't know what that might be.

2018-04-14 17:53 UTC, johndiiorio approved these changes

2018-04-14 17:54 UTC, merged