Made them comments
OpenEnergyDashboard/OED pull request #393
Opened 2019-02-25 16:15 UTC by Zeewild

Added them comments.

2019-02-26 16:46 UTC, NoraCodes requested changes
This basically looks OK to me, barring the requested changes, but I might suggest pulling out the comments on the `render()` functions into some external document that describes how we use React for document structure, since they are repetitious.

Also, these commit messages are somewhat uninformative. There's a good guide on how to write useful commit messages [here](https://chris.beams.io/posts/git-commit/).

2019-02-26 16:46 UTC, NoraCodes commented on src/client/app/components/ChartLinkComponent.tsx
> + * Is the link visible?
I think it makes more sense to put this comment on the actual line with the `showLink` field definition, or to annotate it, like:
```
/**
 * The type used to represent the state of a ChartLinkComponent.
 * showLink: whether the link is visible or not.
 */

2019-02-26 16:46 UTC, NoraCodes commented on src/client/app/components/ChartSelectComponent.tsx
> + * Calls method to change the type of chart when a chart is selected.
This is a type definition; it doesn't call anything.

2019-02-26 16:46 UTC, NoraCodes commented on src/client/app/components/LoginComponent.tsx
> + * Creates components used by the LoginState
This is a type definition. It doesn't actually execute; rather, it's used to make sure we didn't access variables that don't exist, or use the variables that _do_ exist in the wrong way.

Check out the comments on the type definitions on src/client/app/types to see how comments for these might look.

2019-02-26 16:46 UTC, NoraCodes commented on src/client/app/components/admin/AddMetersComponent.tsx
> +	 * Takes an array of type "File" as "files" and does something to handle it.
The "something" here is:
1. checks that the string is really there
2. splits it on line endings
3. grabs the IPs of all the meters in the file
4. submits those IPs as new meters

2019-02-26 16:46 UTC, NoraCodes commented on src/client/app/styles/spinner.css
> +/* Creates general spinner visuals, used and modified by spinner-item-1 and spinner-item-2 */
As a declarative element, I would swap "creates" for "specifies", or simply remove it: "General spinner visuals..."

2019-02-27 00:17 UTC, jameeters commented on src/client/app/components/ExportComponent.tsx
> +	 */
The difference is between functional and class-based components. https://reactjs.org/docs/components-and-props.html

2019-02-27 00:22 UTC, jameeters commented
I think the usage of `render()` is pretty well covered in the react docs, and our wiki already points to those docs, so I don't think we should have our own homebuilt react documentation. I think the comments on `render` can be safely dropped.

2021-03-06 18:17 UTC, huss commented
These comments were not merged at the time (my fault) and are now out of date so some no longer apply (we changed graphics package). Also, there remains a moderate number of TODO items and the requested changes are not addressed. I appreciate the effort by @Zeewild but given all of this I'm going to close this PR without merging.

2021-03-06 18:17 UTC, closed without merging