Add Maps to OED
OpenEnergyDashboard/OED pull request #502
Opened 2020-08-12 02:38 UTC by ak476519

Introducing maps that graph energy usage by meters and groups of meters. This is documented as an issue and fixes #469.

Inside the admin panel, an image can be uploaded. Then add corresponding GIS coordinates for at least 3 points to calibrate. After a map is created, its info can be modified from a maps tab in the admin panel.
 
The admin can also add GIS coordinates for available meters in the meters panel. The meter will be displayed on a map, if it's inside the map's boundaries. 

This fixes #469. The changes by merging development also fixes #527.

Note merging this changes the node modules. Note merging this changes the database configuration.

2020-09-01 23:38 UTC, ak476519 commented
**Note: further discussion is needed to decide what kind of data will be displayed on the map. 

Currently maps are set to display the same time interval selected in bars and lines, averaged by days. If the range is unbounded, it displays the average usage for the last 4 weeks'(28 days).

2020-09-01 23:42 UTC, ak476519 commented
Other features: 

1. A logging API is added to document calibration process in the log, which includes actions and data input. 
2. Replaced the chart selection buttons with a dropdown menu to hold more options.

2021-01-12 23:59 UTC, huss requested changes
This is nice work that does what it should. Manual testing indicates it works correctly. The automated tests worked fine. I wanted to get these comments out now but I am soon going to try to merge in development because there are conflicts. I hope to resolve the conflicts and update the PR to remove them. I’ll post another comment on this.
Here are a few general comments in addition to the ones on specific parts of the code:
- It would be nice to have more comments in the code.
- The standard check (lint) of code is generating a number of issues.
- The following files have new Meter(...) without the new gps value as an argument: src/server/services/readMacacMeters.js x 1, src/server/test/db/insertMamacReadingsFromCSVTests.js x 1, src/sever/test/db/loadFromCsvStramTests.js x 1, src/server/test/db/metasysTests.js x 3.
- This is a small point but you can enable a map that is not calibrated. It may have generated a log entry with error from the query but I’m not certain. It shows grayed out on the list in the map graphic but it might confuse an admin. Should we stop or warn an admin if they try to enable a map that is not calibrated? This can also be left for a future enhancement (we need to create an issue then).

2021-01-12 23:59 UTC, huss commented on src/server/migrations/0.5.0-0.6.0/preferences/sql/map/create_maps_table.sql
> +	origin POINT,
origin and opposite are DEFAULT NULL in create but not here.

2021-01-12 23:59 UTC, huss commented on src/server/migrations/0.5.0-0.6.0/preferences/sql/map/create_maps_table.sql
> +/* This Source Code Form is subject to the terms of the Mozilla Public
For reasons I don't know, the directory structure is off for migrations. It should be src/server/migrations/0.50-0.6.0/sql (not src/server/migrations/0.50-0.6.0/preferences/sql). I don't think you created this but can you please fix this up.

2021-01-12 23:59 UTC, huss commented on src/server/sql/meter/create_meters_table.sql
> +	gps POINT
In migrations, gps is DEFAULT NULL but not here

2021-01-12 23:59 UTC, huss commented on src/client/app/actions/logs.ts
> +export function logToServer(level: string, message: string, error?: Error, skipMail?: boolean) {
It would be nice to have some comment on what this does/is for.

2021-01-12 23:59 UTC, huss commented on src/client/app/actions/map.ts
> +
Some comments would help.

2021-01-12 23:59 UTC, huss commented on src/client/app/components/DashboardComponent.tsx
>  // TODO lowercase plotly for the import in index.d.ts but uppercase here.
I think this comment is now obsolete so can be removed?

2021-01-12 23:59 UTC, huss commented on src/client/app/components/DashboardComponent.tsx
> +		} else {
This is similar logic to before but it does mean if someone makes a mistake in the chartToRender you get a map. At some point we should have a default that deals with errors?

2021-01-12 23:59 UTC, huss commented on src/client/app/components/maps/MapCalibrationComponent.tsx
> +					<HeaderContainer />
Some /> have space  before and some do not. Reason?

2021-01-12 23:59 UTC, huss commented on src/client/app/components/maps/MapCalibration_InfoDisplayComponent.tsx
> +			this.props.log('info', 'refused data point with invalid input');
Would be good if told invalid GPS provided in log msg.

2021-01-12 23:59 UTC, huss commented on src/client/app/components/maps/MapCalibration_InitiateComponent.tsx
> +			console.log(err);
Should this msg also include the context in which the error occurred.

2021-01-12 23:59 UTC, huss commented on src/client/app/components/maps/MapViewComponent.tsx
> +
extra blank line.

2021-01-12 23:59 UTC, huss commented on src/client/app/components/maps/MapViewComponent.tsx
> +
extra blank lines.

2021-01-12 23:59 UTC, huss commented on src/client/app/actions/mapReadings.ts
> +		console.log(mapDuration);
Is this for debugging (so should be removed) or should it be changed to use the logging system?

2021-01-12 23:59 UTC, huss commented on src/client/app/containers/MapChartContainer.ts
> +				// console.log(state.meters.selectedMeters);
remove log statements?

2021-01-12 23:59 UTC, huss commented on src/client/app/containers/MapChartContainer.ts
> +			// map coordinates to individual traces, todo: finalize mapping function
Is this todo an issue?

2021-01-12 23:59 UTC, huss commented on src/client/app/containers/MapChartContainer.ts
> +			const trace1 = {
I prefer not to have variable names that end with a number, esp. 1 since it looks like l.

2021-01-12 23:59 UTC, huss commented on src/client/app/containers/RouteContainer.ts
> +		defaultLanguage: state.admin.defaultLanguage,
I'm not generally commenting when lint shows an issue but this added comma is not needed.

2021-01-12 23:59 UTC, huss commented on src/client/app/containers/maps/MapCalibration_ChartDisplayContainer.ts
> +	for (const point of event.points) {
I'm not clear on why multiple points are in the event and then it seems you use the first one [0] in the end. Could you put in comment to explain this?

2021-01-12 23:59 UTC, huss commented on src/client/app/containers/maps/MapCalibration_InfoDisplayContainer.ts
> +	const currentCartesianDisplay =(map.currentPoint)? `x: ${map.currentPoint.cartesian.x}, y: ${map.currentPoint.cartesian.y} ` : 'undefined';
Should there be a space in ".y} `"?

2021-01-12 23:59 UTC, huss commented on src/client/app/utils/calibration.ts
> +	const array = input.split(',').map((value: string) => parseFloat(value));
What happens of value is not a float so parseFloat fails? Should there be a test to verify there are only two values (meaning 1 comma) in input?

2021-01-12 23:59 UTC, huss commented on src/client/app/utils/calibration.ts
> +	const deltaLongitude = p1.gps.longitude - p2.gps.longitude;
Most places in the code do X first and X is the first value returned so I would put the X calculation first.

2021-01-12 23:59 UTC, huss commented on src/client/app/utils/calibration.ts
> +		res = {
Could res = ... be after the if since both do this?

2021-01-12 23:59 UTC, huss commented on src/server/models/patch-point-type.js
> +		function (val) {
Should this and comment above be one less indent? Seems function body should all be one more indent than function declaraton.

2021-01-12 23:59 UTC, huss commented on src/server/routes/meters.js
> +			// .json({ message: 'Invalid meter data supplied.', err: validatorResult.errors });
What is the status of this comment that removed code previously there?

2021-01-16 19:05 UTC, huss commented
I have now completed the merging of development (see commits for what it addresses). All tests now pass and note that the changes also fixed the tests that were failing after the upgrade of pg-promise. Once the relatively straightforward comments are addressed this should be ready to merge.

2021-01-26 23:53 UTC, ak476519 commented on src/client/app/components/DashboardComponent.tsx
> +		} else {
Changed to throwing an error if someone makes a mistake in the following commit [https://github.com/OpenEnergyDashboard/OED/pull/502/commits/ede0d2e6690a7b24b7ff2157bf6b3b74dc54d689](url)

2021-02-11 02:00 UTC, ak476519 commented on src/client/app/utils/calibration.ts
> +	const deltaLongitude = p1.gps.longitude - p2.gps.longitude;
That's fair, I put X calculation first because latitude comes before longitude.

2021-02-11 02:00 UTC, ak476519 commented on src/client/app/utils/calibration.ts
> +	const array = input.split(',').map((value: string) => parseFloat(value));
I've added tests before these lines to make sure there are only two values(1 comma) in input.
As for this part, parseFloat will return NaN if the parsed value is not number, NaN will turn out false when compared with everything, so an invalid value will trigger the warning as expected.

2021-02-11 05:23 UTC, ak476519 commented on src/server/routes/meters.js
> +			// .json({ message: 'Invalid meter data supplied.', err: validatorResult.errors });
It was a log.json function call that didn't seem to trigger during testing, I made a change but decided to keep the original format. Now it's been removed.

2021-02-25 20:51 UTC, huss commented on src/client/app/actions/map.ts
> +
good enough

2021-02-25 21:04 UTC, huss commented on src/client/app/containers/MapChartContainer.ts
> +			const trace1 = {
Changed trace1 to traceOne

2021-02-25 21:08 UTC, huss commented on src/client/app/containers/maps/MapCalibration_ChartDisplayContainer.ts
> +	for (const point of event.points) {
comment added by @ak476519 so done.

2021-02-25 21:13 UTC, huss commented on src/client/app/utils/calibration.ts
> +	const array = input.split(',').map((value: string) => parseFloat(value));
Addressed by @ak476519. I added comment about why it works.

2021-02-25 21:14 UTC, huss commented on src/client/app/utils/calibration.ts
> +	const deltaLongitude = p1.gps.longitude - p2.gps.longitude;
Addressed by @ak476519.

2021-02-25 21:16 UTC, huss commented on src/server/models/patch-point-type.js
> +		function (val) {
I auto-formatted to fix.

2021-02-26 00:10 UTC, huss commented
Since many PRs were merged after the original review of this PR, I merged in development and dealt with a lot of conflicts. I also addressed a few minor outstanding comments on PR as well as fixed a bug in the values used for the circle on a map. It now seems to work correctly and locally passes all checks/tests. No issues or review items are left.

2021-02-26 00:10 UTC, huss approved these changes

2021-02-26 00:11 UTC, merged