Lindavin/testing data
OpenEnergyDashboard/OED pull request #505
Opened 2020-10-14 14:23 UTC by lindavin

This pull request adds a way to generate testing data so that developers can have a visual test on OED. Currently it only generates a sine function over time.

2020-11-25 22:23 UTC, huss requested changes
This code works well. I have asked for a number of changes or made suggestions in my review. Note that some are marked Outdated but that seems to be from @lindavin doing a commit after I make the comment. As such, they should still be looked at. I did the testing on my machine and it runs correctly (with suggested changes). I also loaded the test data in OED. It looks fine but there are some issues that will be addressed outside this PR. This code may be altered in the future to generate more types of sample data as we do more testing on OED. It is also intended to be used to all for more systematic testing of OED in the automated tests rather than just using a few simple points.

2020-11-25 22:23 UTC, huss commented on src/server/data/generateTestData.js
> + *
I think we prefer not to have final, empty lines in comments.

2020-11-25 22:23 UTC, huss commented on src/server/data/generateTestData.js
> + * 1. Generate the moments in time within a specificed range and at a specified time step from a given range.
specificed (sp).

2020-11-25 22:23 UTC, huss commented on src/server/data/generateTestData.js
> + * 		Conceptually this is sin(decimal_percentage * 2*PI) and it works because the sine function we will
Maybe consistent spaces around * in formula?

2020-11-25 22:23 UTC, huss commented on src/server/data/generateTestData.js
> +		throw Error('The timestep needs to be at least 1 second.')
I think it is always a good idea to provide as much information as possible in an error message. Here I would add the timeStep provided.

2020-11-25 22:23 UTC, huss commented on src/server/data/generateTestData.js
> +	while (!startMoment.isAfter(endMoment)) {
Would this be clearer and simpler as
endMoment.isAfter(startMoment)

2020-11-25 22:23 UTC, huss commented on src/server/data/generateTestData.js
> +	if (endTime - startTime <= 0) { return 1 };
This test seems to overlap the above checks. I don't see how endTime - startTime could be negative given you check endTime before startTime and startTime after endTime. I do see that the case of them being equal is not caught above and needs to be done (there is the isSame() function). I think it needs to be decided if === is an error or should return 1 given currentMoment must equal the other two in this case.

2020-11-25 22:23 UTC, huss commented on src/server/data/generateTestData.js
> + * @param {Object} period_length Object whose keys describe the length of the
describe the length of the period (?)

2020-11-25 22:23 UTC, huss commented on src/server/data/generateTestData.js
> + * @returns {Number[]} an array where each element corresponds to the percentage of time elasped at the
elasped (sp)

2020-11-25 22:23 UTC, huss commented on src/server/data/generateTestData.js
> + * @param {String} startTimeStamp, the time's format is 'YYYY-MM-DD HH:MM:SS'
I think these comments could better describe how the TimeStamps are used and what values are valid for options along with the defaults (amplitude not given above).

Probably should remove the , after the variable names.

2020-11-25 22:23 UTC, huss commented on src/server/data/generateTestData.js
> +	const defaultOptions = {
I  may be missing something but it seems the default options are set in both the arguments and here. If so, would it be safer to only set in one place so it only has to be changed in one place? See how done another way in generateSine.

Also, is defaultOptions a good name if it might be the default ones or the ones passed? Is it the usedOptions?

2020-11-25 22:23 UTC, huss commented on src/server/data/generateTestData.js
> +			const scaledResult = halfMaxAmplitude * (isEpsilon(result) ? 0 : result) + halfMaxAmplitude;
I'm curious why you make small values 0. I can see that you get roundoff/precision errors with sin but they should be very small. Also, they will occur at all values including ones close to 1. Given this, should we just accept the sin result? Maybe there is an idea here I am missing.

I did have the thought that you want this to go to 0 for testing to compare to an integer. If that is the case then maybe changing the test to do a close to equal (such as .closeTo) might be better.

2020-11-25 22:23 UTC, huss commented on src/server/data/generateTestData.js
> +			return console.log(err);
I wonder if this should cause an exception so any code calling this code knows an error occurred. generateDates does that.

2020-11-25 22:23 UTC, huss commented on src/server/data/generateTestData.js
> + * @param {Object} options, options is an object that will be parsed by
Are all the options parsed by moment or just the ones that represent a time stamp? I think here and/or somewhere else that is referenced (if document some elsewhere as suggested), the meaning of each option should be given.

2020-11-25 22:23 UTC, huss commented on src/server/data/generateTestData.js
> +	_generateSineData
I see you use _generateSineData in testing but it seems a little funny to export a function with _ that normally means it is for internal use/private. I don't know if there is a better way to do this.

2020-11-25 22:23 UTC, huss commented on src/server/test/generateTestDataTests.js
> +	mocha.it('should be able to generate dates at a time step 15 seconds', () => {
I like these tests but both hit the endTimeStamp exactly. Should one have it so it is not the case that endTimeStamp = startTimeStamp + n * timeStep, where n is an integer?

2020-11-25 22:23 UTC, huss commented on src/server/test/generateTestDataTests.js
> +		expect([1]).to.deep.equals(momenting(periodOfMoments));
It seems you are calling momenting with one argument but it should take two. Is this correct?

2020-11-25 22:23 UTC, huss commented on src/server/test/generateTestDataTests.js
> +		expect(momenting(test.map(timeStamp => moment(timeStamp)), timeStepMs)).to.deep.equals([0, 1, 1]);
Small point but in the first two tests you put the expected array first and in the second two you put it last.

2020-11-25 22:23 UTC, huss commented on src/server/test/generateTestDataTests.js
> +mocha.describe('Generate sinewave helper', () => {
sinewave -> sine wave, below is similar in next test.

2020-11-25 22:23 UTC, huss commented on src/server/data/generateTestData.js
> +		array_of_moments.push(startMoment.format('YYYY-MM-DD HH:mm:ss'));
Should be arrayOfMoments here and below. Editing oversight when linting issues were resolved in recent commit.

2020-11-25 22:23 UTC, huss commented on src/server/data/generateTestData.js
> +function write_to_csv(data, filename = 'test.csv') {
I think this function name should be changed to remove _ and use camelcase to be consistent with variable name changes from linting rules.

2020-11-25 22:23 UTC, huss commented on src/server/test/generateTestDataTests.js
> +	mocha.it('should properly write to file', async () => {
Took me a little while to figure out this mistake. period_length -> periodLength.

2020-11-25 22:23 UTC, huss commented on src/server/data/generateTestData.js
> +			log.info('The file was saved!');
I think this message (and the error ones above) should have more information. It should say the file name and that it was doing test data generation. This is needed because the log file has lots of output and it is not easy to tell where a message came from without context.

2020-11-25 22:23 UTC, huss commented on src/server/test/generateTestDataTests.js
> +		await generateSine(startTimeStamp, endTimeStamp, { ...timeOptions, filename: filename, maxAmplitude: maxAmplitude });
filename: filename -> filename: `${__dirname}/${filename}`
Below the code reads from this location. Docker may write a file (by default) in the main directory of the application where it is started. This often is not the src/server/test directory. Since we don't want the test data file in another directory, I think we should do this change. I tested it on my machine and it worked properly. See below for another comment.

2020-11-25 22:23 UTC, huss commented on src/server/test/generateTestDataTests.js
> +
I wonder if we should delete the test output file after it is read for several reasons. First, if a file is left over from previous testing then it may be reused if this test fails before the file write and it could pass when it should not. Second, the file shows up as a change in git that might lead to it being put onto GitHub. Third, leaving around files may not be a good idea (it is very nice during debugging to see the output but not in general). Another option would be to use the date/time as part of the file name but I think it is best to delete it.

2020-12-01 16:15 UTC, huss commented
I have been looking at and analyzing the graphs more. The line graph you get (see issue #519) has values from 0-6 even thought the generated values are 0-2. The reason is that OED takes the reading which is kW and converts it to kWh. Since each reading is 20 minutes, it scales the reading by dividing by 20/60 (fraction of an hour that each point represents) so each reading is graphed as reading/(20/60) or reading * 3. Since the intent was the test code would generate data with a given amplitude, I think we should normalize it by the fraction of an hour represented (the inverse of what OED is doing) so we see the expected amplitude on the graph and the actual readings will not be these values.

2020-12-01 16:25 UTC, huss commented
I used the test data to actually test OED. It was useful to create sin^2 and cos^2 so I could create a group that is the sum that should then be the sum of these amplitudes since sin^2 + cos^2 is 1. While it is not hard to get cos from sin, I think it would be good to have a way to get the cos as we do sin in the test code. This could either be a new function or one adding a parameter to choose which the user wants (with renaming of the functions).  The user can easily do the square of each point if that is what they want.

2020-12-10 17:53 UTC, huss commented
This is a major step in doing #141. We will need to integrate this data fully into OED to finish that process.

2020-12-13 01:24 UTC, lindavin commented
Now testing data is rewritten in typescript, the cosine function is added, and a new parameter to normalize data for OED has been added.

2021-01-17 01:10 UTC, lindavin commented on src/server/test/generateTestDataTests.js
> +		expect([1]).to.deep.equals(momenting(periodOfMoments));
I thought that this would be okay since I just wanted to test the singleton case which would have no period length.

2021-01-17 02:10 UTC, lindavin commented on src/server/data/generateTestData.js
> +			const scaledResult = halfMaxAmplitude * (isEpsilon(result) ? 0 : result) + halfMaxAmplitude;
There is no deep.closeTo implemented for chai so instead I used a loop with closeTo.

2021-01-17 02:21 UTC, lindavin commented on src/server/test/generateTestDataTests.js
> +	mocha.it('should be able to generate dates at a time step 15 seconds', () => {
Okay, I changed the time step to 13 minutes which should work since there is an integer amount of hours between the end and start timestamps.

2021-01-17 02:22 UTC, lindavin commented on src/server/test/generateTestDataTests.js
> +		expect([1]).to.deep.equals(momenting(periodOfMoments));
I added `undefined` as the second parameter for this reason.

2021-01-19 00:18 UTC, huss approved these changes
I merged with development and it runs fine. All tests are passing locally. Since these changes are independent of other PRs ahead of it, it is okay to merge now. I thank @lindavin for working on this and adding features added after initial development.

2021-01-19 00:18 UTC, huss commented on src/server/data/generateTestingData.ts
> + * generateSine,
You added generateCosine in last revisions.

2021-01-19 00:18 UTC, huss commented on src/server/data/generateTestingData.ts
> +		phaseShift: (options.phaseShift || 0) + (Math.PI / 2)
I might put a comment here that this shifts sine to cosine by adding pi/2.

2021-01-19 00:18 UTC, huss commented on src/server/data/generateTestingData.ts
> + * 		Conceptually this is sin(decimal_percentage * 2* PI) and it works because the sine function we will
space before *

2021-01-19 00:18 UTC, huss commented on src/server/data/generateTestingData.ts
> +		throw Error(`The time step provided is ${JSON.stringify(timeStep)} needs to be at least 1 second.`);
throw new Error. Several others below.

2021-01-19 00:21 UTC, merged