Tooltips
OpenEnergyDashboard/OED pull request #506
Opened 2020-10-27 15:27 UTC by lindavin

This pull request implements the tooltips on the home page. For some tooltips we use the TooltipHelpComponent. In other positions on the home page, it was easier to use an alternative implementation of tooltips: TooltipHelpComponentAlternative.

2020-11-27 07:31 UTC, sasankthapa commented
I think everything is working as intended but there are some minor issues about styling like:

![image](https://user-images.githubusercontent.com/53589226/100422481-08516100-3050-11eb-8aa0-62e0360c27c2.png)

The buttons on the graph are messing with the texts and most of the links are wrapped outside the box.

2020-12-08 15:42 UTC, huss commented
While it would be nice to fix the formatting to avoid going outside the tooltip box, I suspect the box size is set and the link URL is too long. I think an easy fix that also makes sense is to use a name/words that link to the help page. The URL was put there to help plan the help page location but I don't see a lot of value in having it in the actual tooltip. Thus, I will edit the tooltip text to fix this and add it as needed.

As for the items on the page showing behind the tooltip and making it harder to read, I suspect this is designed to allow people to see the page while reading the tooltip. We could change (if that is an option) so the tooltip background is solid but I don't know if we want that all the time. I'm open to suggestions here.

2021-01-23 23:22 UTC, huss requested changes
The review chages are not showing up on GitHub so maybe I forgot to finish review. Doing it now.

2021-01-23 23:22 UTC, huss commented on src/client/app/components/ChartLinkComponent.tsx
> +import TooltipHelpComponent from './TooltipHelpComponent';
This import does not seem to be used.

2021-01-23 23:22 UTC, huss commented on src/client/app/components/DashboardComponent.tsx
> +import TooltipHelpComponent from './TooltipHelpComponent';
import does not seem to be used.

2021-01-23 23:22 UTC, huss commented on src/client/app/components/HeaderButtonsComponent.tsx
> +import TooltipHelpComponent from './TooltipHelpComponent';
This and next imports do not seem to be used.

2021-01-26 00:02 UTC, huss commented
This PR is now complete. It will likely be merged after the PRs that came before it (or sooner) and slated for version 0.7. I will do the final checks to be sure merging in the current development does not cause any issues.

I want to thank @lindavin for doing all of this and making changes as new ideas were thought of.

2021-02-07 16:18 UTC, huss commented
I have reviewed the recent changes (that I asked for). All still seems fine. Note I may be changing the links in the tooltips as I create the help pages and desire changes.

2021-02-21 17:34 UTC, huss approved these changes
I have looked these over and all is fine. Changes requested plus more done.

2021-02-21 18:04 UTC, merged