PR for Database changes for meters, maps, and groups. Models are modified to accommodate the DB changes. Additionally, test code and test date script was modified/created(1).
OpenEnergyDashboard/OED pull request #632
Opened 2021-04-29 23:35 UTC by wadoodalam

# Description

(Please include a summary of the change and which issue is touched on. Please also include relevant motivation and context.)

Fixes #[issue]

(In general, OED likes to have at least one issue associated with each pull request. Replace [issue] with the OED GitHub issue number. In the preview you will see an issue description if you hover over that number. You can create one yourself before doing this pull request. This is where details are normally given on what is being addressed. Note you should not use the word "Fixes" if it does not completely address the issue since the issue would automatically be closed on merging the pull request. In that case use "Partly Addresses #[issue].)

## Type of change

(Check the ones that apply by placing an "x" instead of the space in the [ ] so it becomes [x])

- [ ] Note merging this changes the node modules
- [ ] Note merging this changes the database configuration.
- [ ] This change requires a documentation update

## Checklist

(Note what you have done by placing an "x" instead of the space in the [ ] so it becomes [x]. It is hoped you do all of them.)

- [ ] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [ ] I have removed text in ( ) from the issue request

## Limitations

(Describe any issues that remain or work that should still be done.)

2021-04-29 23:41 UTC, wadoodalam commented
Database changes for meters, maps, and groups. 
Models are modified to accommodate the DB changes. Additionally, the test code and test date script was modified/created(1 test in web/groups.js needs a fix).

2021-05-03 16:31 UTC, huss requested changes
There are a fair number of issues that need to be carefully addressed in this PR. I have not yet tested the code functions properly but wanted to get these comments to the author.

2021-05-03 16:31 UTC, huss commented on src/server/migrations/0.6.0-0.7.0/sql/group/add_displayable,gps,note,area_columns.sql
> +/* This Source Code Form is subject to the terms of the Mozilla Public
This file name is not consistent with other OED files. There should not be commas in the name.

2021-05-03 16:31 UTC, huss commented on src/server/migrations/0.6.0-0.7.0/sql/group/add_displayable,gps,note,area_columns.sql
> +    ADD COLUMN IF NOT EXISTS note VARCHAR(500),
From the documentation, VARCHAR(#) and TEXT are internally stored the same way in Postgres. It seems best to use TEXT unless you have a reason to restrict the length of the attribute. Given we have a limited number of groups, meters, etc., I don't see a reason to limit the length of the note. We just have to be careful to allow for longer ones when we display on the admin page. Thus, can you please change this to TEXT. Also, please make the same change with migrations for the note in meters and maps tables. The other uses of VARCHAR in OED are probably reasonable since the actual item should be of limited length so we will not change those.

2021-05-03 16:31 UTC, huss commented on src/server/migrations/0.6.0-0.7.0/sql/group/add_displayable,gps,note,area_columns.sql
> +    ADD COLUMN IF NOT EXISTS area FLOAT(8) DEFAULT NULL;
FLOAT(#) in most DB systems (including Postgres) is somewhat misleading to use since it generally either goes to single or double precision. OED is not 100% consistent but it tends to use REAL (double precision) for values. It has not used (FLOAT(#). Given the limited number of rows, I see no reason not to use REAL here (note we use REAL in readings and that is a lot of rows).

2021-05-03 16:31 UTC, huss commented on src/server/migrations/0.6.0-0.7.0/sql/map/add_column_north_angle and circe_fraction.sql
> +	ADD COLUMN IF NOT EXISTS north_angle FLOAT(8) DEFAULT 0.0,
FLOAT(8)->REAL

2021-05-03 16:31 UTC, huss commented on src/server/migrations/0.6.0-0.7.0/sql/map/add_column_north_angle and circe_fraction.sql
> +/* This Source Code Form is subject to the terms of the Mozilla Public
File name has spaces and circe is mispelled. Please make it consistent with OED file names.

2021-05-03 16:31 UTC, huss commented on src/server/migrations/0.6.0-0.7.0/sql/meter/add_multiple_db_meters_columns.sql
> +	ADD COLUMN IF NOT EXISTS note VARCHAR(500),
varchar→text and float(8)->real.

2021-05-03 16:31 UTC, huss commented on src/server/sql/meter/create_meters_table.sql
> +	end_timestamp TIMESTAMP DEFAULT '0001-01-01 : 00:00:00'
extra spaces at end of line.

2021-05-03 16:31 UTC, huss commented on src/server/sql/meter/create_meters_table.sql
>  CREATE TABLE IF NOT EXISTS meters (
I know the original file had tabs but all indent should be spaces in SQL files.

2021-05-03 16:31 UTC, huss commented on src/server/migrations/0.6.0-0.7.0/sql/meter/add_multiple_db_meters_columns.sql
> +    ADD COLUMN IF NOT EXISTS cumulative_reset_end TIME DEFAULT '23:59:50',
Per current version of design document, the end time should be 23:59:59.999999, If cannot have decimal on then 23:59:59.
Also make sure reading variation has a consistent default value.

2021-05-03 16:31 UTC, huss commented on src/server/models/Map.js
> +	 * @param maxCircleSizeFraction Stores the fraction of horizontle map
horizontal sp.

2021-05-03 16:31 UTC, huss commented on src/server/models/Meter.js
> +	 * @param reading The value of reading
reading, startTimestemp & endTimestamp are the last reading input for this meter into OED. The comment should reflect this.

2021-05-03 16:31 UTC, huss commented on src/server/models/Meter.js
> +	 * @param cumulative Checks if the reading is a sum of usage or the particular reading
This should be "Identifies if meter readings that are stored are the sum of usage...."

For this and following values, I think it would be good to identify which ones will default to a value (via the DB) if no value is given (does that mean unknown or null?).

2021-05-03 16:31 UTC, huss commented on src/server/models/Meter.js
> +	 * @param previousDay Checks if the if the reading is of the previous day
The wording of this comment is off but that does not really matter since the latest design document does not have this value.

2021-05-03 16:31 UTC, huss commented on src/server/models/Map.js
> +	 * @param northAngle stores angle between map orientation and true north
For this and following value, I think it would be good to identify which ones will default to a value (via the DB) if no value is given (does that mean unknown or null?).

2021-05-03 16:31 UTC, huss commented on src/server/sql/meter/create_meters_table.sql
> +cumulative_reset:		True if pipline is to be reset
I think a better comment is "True if cumulative values can reset back to zero."

2021-05-03 16:31 UTC, huss commented on src/server/sql/meter/create_meters_table.sql
> +reading: 				The reading from the meter
Make sure these comment and other items from migration get into this file.

2021-05-03 16:31 UTC, huss commented on src/server/sql/meter/get_meter_by_id.sql
> +SELECT id, name, ipaddress, enabled, displayable, meter_type, default_timezone_meter, gps, identifier, note, area, cumulative, cumulative_reset, cumulative_reset_start, cumulative_reset_end, previous
This line is too long. Create multiple lines.

2021-05-03 16:31 UTC, huss commented on src/server/sql/meter/get_meter_by_name.sql
> +SELECT id, name, ipaddress, enabled, displayable, meter_type, default_timezone_meter, gps, identifier, note, area, cumulative, cumulative_reset, cumulative_reset_start, cumulative_reset_end, previous
This line is too long. Create multiple lines.

2021-05-03 16:31 UTC, huss commented on src/server/sql/meter/insert_new_meter.sql
> +INSERT INTO meters(name, ipaddress, enabled, displayable, meter_type, default_timezone_meter, gps, identifier, note, area, cumulative, cumulative_reset, cumulative_reset_start,cumulative_reset_end, p
These lines are too long. Create multiple lines.

2021-05-03 16:31 UTC, huss commented on src/server/sql/reading/create_compressed_reading_views.sql
> +
No tabs on blank lines.

2021-05-03 16:31 UTC, huss commented on src/server/sql/reading/create_compressed_reading_views.sql
> +	/* Change the code below and get meterid, readings, start and end timestamp from readings table instead(raw data)*/
These are changes outside this PR so the comments need to be removed.

2021-05-03 16:31 UTC, huss commented on src/server/test/db/groupTests.js
> +	const groupA = new Group(undefined, 'A', true, gps, 'notes', 33.5);
While it really isn't important, if it is group A, B, C then I think it should be notes A, notes B, notes C.

2021-05-03 16:31 UTC, huss commented on src/server/test/db/groupTests.js
> +	'Identified 1' ,'Notes', 35.0, true, true, '01:01:25' , '00:00:00', true, '05:00:00','00:00:00', 1.5,
First, in this and the following three meter creation you are inconsistent in identified name. Also, please make them consistent with meter name per group comment above. Second, make note names consistent in same way. Third, the timestamp has a colon between the data and time. I think that is not the normal syntax. Fourth, the start_timestamp has invalid dates (year and day).

2021-05-03 16:31 UTC, huss commented on src/server/test/db/mapTests.js
> +		const mapPreInsert = new Map(undefined, 'Map', false, null, 'default', moment('2000-10-10'), origin, opposite, 'placeholder', 22.5, 10.5);
The fraction should be 0-1. While it does not change the test, I think it is best to use valid values unless testing otherwise.

2021-05-03 16:31 UTC, huss commented on src/server/test/db/meterTests.js
> +		const meterPreInsert = new Meter(undefined, 'Meter', null, false, true, Meter.type.MAMAC, 'UTC',
Please see groupTests.js for comments on dates that impact several places in this file.

2021-05-03 16:31 UTC, huss commented on src/server/test/db/meterTests.js
>  }
I'm unclear on why the last three attributes of the meters table involving reading are not verified.

2021-05-03 16:31 UTC, huss commented on src/server/test/web/groups.js
> +		groupA = new Group(undefined, 'A', true, gps, 'notes', 33.5);
Please see comment in groupTests.js about Group and Meter values that apply to this file.

2021-05-03 16:31 UTC, huss commented on src/server/test/web/groups.js
> +		// For the test below: AssertionError: expected [ Array(3) ] to be a superset of [ Array(3) ]
Please add the PR description under limitations that this test is failing.

2021-05-03 16:31 UTC, huss commented on src/server/test/web/maps.js
> +		expect(map).to.have.property('northAngle');
I think it is worth making sure the value is what is expected for both these new properties.

2021-05-03 16:31 UTC, huss commented on src/server/test/web/maps.js
> +		await new Map(undefined, 'Map 1', true, null, 'default', moment('2000-10-10'), origin, opposite, 'placeholder', 0.0, 0.0).insert(conn);
I think at least one of the tests should have maps where the new values are not just 0.0.

2021-05-03 16:31 UTC, huss commented on src/server/test/web/meters.js
> +		await new Meter(undefined, 'Meter 1', '1.1.1.1', true, true, Meter.type.MAMAC, 'TZ1', gps,
See groupTests.js for issues on Meter creation values that apply here.

2021-05-03 16:31 UTC, huss commented on src/server/test/web/meters.js
> +		'0011-05-022 : 23:59:59', '2020-07-02 : 01:00:10').insert(conn);
I cannot comment on lines you did not change so I'm putting this comment here. I think you really should be testing the new meter values. You added them to the meters you created but you never verify they have the correct values as the previous values did. I'm also uncertain why some meter have the new values and others were not changed.

2021-05-05 15:13 UTC, huss commented
I have pushed a number of commits to the PR to address:
- A few issues not completed by @wadoodalam that are in the review including removal of previous day per design document
- Remove .DS_Store Mac file that should not be in repo (seems added via this PR) and caused check failure
- Improved/fixed some existing testing and add tests for some new DB items in the PR. This includes fixing the test that failed and noted in the PR description (now edited)
- I note that there are a lot of instances of creating meters, groups & maps that do not pass the new arguments. I have created issue #635 so it can be addressed at some point.

2021-05-05 15:57 UTC, huss approved these changes

2021-05-05 15:57 UTC, huss commented
I have completed local testing and it seems to run fun. I believe this is ready to merge.

2021-05-05 15:57 UTC, merged