Map changes
OpenEnergyDashboard/OED pull request #661
Opened 2021-10-25 23:06 UTC by jina2k

# Description

Fixes #609 : If only one map exists, automatically display map.
Fixes #606 : Sorted map names alphabetically
Fixes #543 : Implemented north angle into calibration. Instead of using the default 0.0 angle, now we use the provided true north angle from the user during calibration. Most of the code was left untouched as it was mostly implemented already, the parameters were just changed to account for this new angle.

## Type of change

- [ ] Note merging this changes the node modules
- [ ] Note merging this changes the database configuration.
- [x] This change requires a documentation update

Note: for the documentation update it should provide info on figuring out the angle (ie; it should correctly calibrate within 3 points, or show a picture side by side to represent 90 degree rotation) and also mentioning that the north angle is no longer defaulted to 0.0. In addition, the test documentation should maybe remove using x,y provided by the grid to find the points, where you would normally divide by 10 and reverse the x,y to y,x. This use case would not work with rotated maps, and should either be removed or modified to address these changes.

## Checklist

- [x] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [x] I have removed text in ( ) from the issue request

## Limitations
n/a

2021-10-29 16:31 UTC, huss requested changes
I have checked that map rotations work with my test maps I used when that feature was added. Everything worked fine. The other changes also seem to work fine from testing. This is good work where a few small changes are requested.

2021-10-29 16:31 UTC, huss commented on src/client/app/components/maps/MapCalibrationInitiateComponent.tsx
> +			if (parseFloat(this.state.angle) > 360) {
I think the check should also make sure it is at least zero. The bad number check gets negative values but the popup says it is not a number which isn't really the case. I think this check should catch that case if not too hard to do.

2021-10-29 16:31 UTC, huss commented on src/client/app/containers/MapChartSelectContainer.ts
> +
extra blank line?

2021-10-29 16:31 UTC, huss commented on src/client/app/translations/data.json
> +		"map.bad.number": "Not a number, please change angle to a number between 0 and 360",
The three new strings are in en & fr but missing from es.

2021-10-29 17:55 UTC, jina2k commented on src/client/app/components/maps/MapCalibrationInitiateComponent.tsx
> +			if (parseFloat(this.state.angle) > 360) {
added test for negative values

2021-10-29 17:55 UTC, jina2k commented on src/client/app/containers/MapChartSelectContainer.ts
> +
removed blank line

2021-10-29 17:55 UTC, jina2k commented on src/client/app/translations/data.json
> +		"map.bad.number": "Not a number, please change angle to a number between 0 and 360",
readded the strings, it was removed during merging with the translations, and also added additional strings for the test case for negative values

2021-10-30 13:36 UTC, huss commented
I just find one more item. If there is only one map and it is autoselected then all the meters show up as graphable when you first go to the map graphic. If you select any meter then the meter menu corrects to gray out any ungraphable meters. Note this only seems to happen when you first reload OED. Sorry I missed this the first time around.
Also, I have not checked that this works with groups but it might be the same issue.

2021-11-01 04:01 UTC, jina2k commented
> I just find one more item. If there is only one map and it is autoselected then all the meters show up as graphable when you first go to the map graphic. If you select any meter then the meter menu corrects to gray out any ungraphable meters. Note this only seems to happen when you first reload OED. Sorry I missed this the first time around. Also, I have not checked that this works with groups but it might be the same issue.

Fixed it to show only meters/groups that are displayable on map

2021-11-01 18:42 UTC, huss approved these changes
Everything looks good.

2021-11-01 18:42 UTC, merged