Updated Spanish translation
OpenEnergyDashboard/OED pull request #689
Opened 2021-12-18 18:57 UTC by husslede

# Description

Added new Spanish translations

## Type of change

- [ ] Note merging this changes the node modules
- [ ] Note merging this changes the database configuration.
- [ ] This change requires a documentation update

## Checklist

- [x] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [x] I have removed text in ( ) from the issue request

## Limitations

none

2021-12-18 21:00 UTC, huss requested changes
Thank you for doing this. A few small items to address.

2021-12-18 21:00 UTC, huss commented on src/client/app/translations/data.json
> +		"map.notify.calibration.needed": "Nececitar calibración antes de visualizar
Missing end quote and comma.

2021-12-18 21:00 UTC, huss commented on src/client/app/translations/data.json
> +		"group.gps": "Grupo de GPS: (latitud, longitud)",
This translation is fine but it is a group's GPS in this case so maybe GPS de grupo?

2021-12-18 21:00 UTC, huss commented on src/client/app/translations/data.json
> +		"map.bad.digitb": "Menor que 360, por favor cambiar el angúlo a un número entre 0 a 360",
I think this should be Menor que 0 not 360.

2021-12-19 13:30 UTC, husslede commented on src/client/app/translations/data.json
> +		"map.notify.calibration.needed": "Nececitar calibración antes de visualizar
fixed

2021-12-19 13:31 UTC, husslede commented on src/client/app/translations/data.json
> +		"group.gps": "Grupo de GPS: (latitud, longitud)",
fixed

2021-12-19 13:31 UTC, husslede commented on src/client/app/translations/data.json
> +		"map.bad.digitb": "Menor que 360, por favor cambiar el angúlo a un número entre 0 a 360",
thank you for finding that - fixed

2021-12-19 14:02 UTC, huss approved these changes
Thank you to @husslede for continuing to work on Spanish translations. This is now ready to merge.

2021-12-19 14:03 UTC, merged