Unit dropdown
OpenEnergyDashboard/OED pull request #754
Opened 2022-04-18 18:18 UTC by andrew-cline

# Description
Adds a dropdown selection menu on the graphing page for units. The menu has logic for enabling and disabling units depending on compatibility with meters and groups that have been selected.
## Type of change
- [ ] Note merging this changes the node modules
- [ ] Note merging this changes the database configuration.
- [ ] This change requires a documentation update

## Checklist
- [x] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [x] I have removed text in ( ) from the issue request

## Limitations
When selecting a meter the units menu does not update with compatible units. This can lead to issues where a meter is selected when an incompatible unit is selected or accidentally selecting the wrong unit for a meter upon first selection, both of which cause a crash on the front end.

2022-04-19 15:03 UTC, huss requested changes
Thanks to @andrew-cline for this work and PR. Overall, it looks good. The final testing cannot happen until this is integrated with the rest of the new resource generalization code but it seems to work fine. I did notice that when I arbitrary set the selected unit (state.graph.selectedUnit = 101;) in src/client/app/containers/DashboardContainer.ts at the top of mapStateToProps, the initial load of the page showed that as the selected unit but all units were grayed out (including that one) on the unit menu. I'm hoping this is due to how I set the value and it will go away when it is selected normally.

There are a couple of minor/modest things that are requested to be addressed.

2022-04-19 15:03 UTC, huss commented on src/client/app/containers/ChartDataSelectContainer.ts
> +
extra blank lines

2022-04-19 15:03 UTC, huss commented on src/client/app/containers/ChartDataSelectContainer.ts
> +
remove blank line

2022-04-19 15:03 UTC, huss commented on src/client/app/containers/ChartDataSelectContainer.ts
> +		state.graph.selectedMeters.forEach(meter => {
It would seem that the two meter loops could be made one as is done for groups.

2022-04-19 15:03 UTC, huss commented on src/client/app/containers/ChartDataSelectContainer.ts
> +		getVisibleUnitOrSuffixState(state).forEach(o => {
The comments from the design document are mising from here on. It is fine to modify them but there should be comments in the code.

2022-04-19 15:03 UTC, huss commented on src/client/app/containers/ChartDataSelectContainer.ts
> +	const visibleUnitsOrSuffixs = _.filter(state.units.units, function (o: UnitData) {
Suffixs is misspelled.

2022-04-19 15:03 UTC, huss commented on src/client/app/containers/ChartDataSelectContainer.ts
> + * @return {UnitData[]} an array of UnitData
The words just mirror the type declaration before it. Could it be more descriptive (maybe similar to the function comment above)? This is also true in next function.

2022-04-19 15:03 UTC, huss commented on src/client/app/containers/ChartDataSelectContainer.ts
> + * Converts two sets of unitIDs into one sorted array of SelectOptions for the dropdown
I think the plan is that this functioin will be used in several places (why it is exported). Thus, could the comments be less specific to units and more general if this is the case. However, the function sets label and value and also loops based on unit. Is it possible to make this more general? If not, then I don't know if it should be exported for general use by meters and groups.

2022-04-19 15:03 UTC, huss commented on src/client/app/containers/ChartDataSelectContainer.ts
> +
extra blank line here and below.

2022-04-19 15:03 UTC, huss commented on src/client/app/containers/ChartDataSelectContainer.ts
> +}
OED is going to standardize on having a return on the last line so could you please add one?

2022-04-19 15:03 UTC, huss commented on src/client/app/components/ChartDataSelectComponent.tsx
> +			helpSelectUnit: { id: 'help.home.select.unit' }
I appreciate you starting to add the tooltip we want for the new unit menu. However, it is not added later in this file for the TooltipMarkerComponent, in that component nor in the translation file. I would be great if you added it in all these places but, if not, then please remove this.

2022-04-19 15:03 UTC, huss commented on src/client/app/containers/ChartDataSelectContainer.ts
> +	return _.orderBy(finalUnits, ['isDisabled', 'label'], ['asc', 'asc']);
This was not in the design document but I noticed that we have units that are both capitalized and not. It would be nice if they were sorted to ignore this. For example, kW and kWh would not be past Metric ton.

2022-04-20 00:09 UTC, andrew-cline commented on src/client/app/containers/ChartDataSelectContainer.ts
> +
Removed blank lines in the most recent commit.

2022-04-20 00:10 UTC, andrew-cline commented on src/client/app/containers/ChartDataSelectContainer.ts
> +
Removed blank lines in the most recent commit.

2022-04-20 00:10 UTC, andrew-cline commented on src/client/app/containers/ChartDataSelectContainer.ts
> +		state.graph.selectedMeters.forEach(meter => {
Combined the meter loops into one in most recent commit.

2022-04-20 00:10 UTC, andrew-cline commented on src/client/app/containers/ChartDataSelectContainer.ts
> +		getVisibleUnitOrSuffixState(state).forEach(o => {
Added missing comments from the design document in the most recent commit.

2022-04-20 00:11 UTC, andrew-cline commented on src/client/app/containers/ChartDataSelectContainer.ts
> +	const visibleUnitsOrSuffixs = _.filter(state.units.units, function (o: UnitData) {
Fixed misspelling in the most recent commit.

2022-04-20 00:12 UTC, andrew-cline commented on src/client/app/containers/ChartDataSelectContainer.ts
> + * @return {UnitData[]} an array of UnitData
Changed the description for the function in the most recent commit. Let me know if you want it changed further.

2022-04-20 00:14 UTC, andrew-cline commented on src/client/app/containers/ChartDataSelectContainer.ts
> + * Converts two sets of unitIDs into one sorted array of SelectOptions for the dropdown
I'm not really sure how to generalize the function for the other menus. Since the function has to pull from that specific type's redux state.

2022-04-20 00:14 UTC, andrew-cline commented on src/client/app/containers/ChartDataSelectContainer.ts
> +
Removed blank lines in the most recent commit.

2022-04-20 00:15 UTC, andrew-cline commented on src/client/app/containers/ChartDataSelectContainer.ts
> +}
Added return on the last line in the most recent commit.

2022-04-20 00:17 UTC, andrew-cline commented on src/client/app/components/ChartDataSelectComponent.tsx
> +			helpSelectUnit: { id: 'help.home.select.unit' }
Added lines to both the translation file and TooltipMarkerComponent. Also added the appropriate TooltipMarkerComponent call into ChartDataSelectComponent. I was not really sure what link to put in TooltipHelpComponentAlternative so I copied the format from the other ones. If that should be removed let me know.

2022-04-20 00:23 UTC, andrew-cline commented on src/client/app/containers/ChartDataSelectContainer.ts
> +	return _.orderBy(finalUnits, ['isDisabled', 'label'], ['asc', 'asc']);
I figured out a way to get Lodash to sort in that order in the most recent commit.

2022-04-20 14:02 UTC, huss commented
Thanks to @andrew-cline for the quick addressing of the review. They all look good and testing indicates all works fine. This PR is ready to merge.

2022-04-20 14:02 UTC, huss approved these changes

2022-04-20 14:02 UTC, merged