Adds internationalization for the word "here". Issue #702
OpenEnergyDashboard/OED pull request #758
Opened 2022-04-22 19:53 UTC by jbmayor4

# Description

This pull request addresses the bug found in Issue #702. It adds internalization support similar to other areas of OED for the word "here", when it is in reference to a link. This change affects the translation "data.js" as well as the toolTipHelpComponentAlternative for generating help links.

Fixes #[702]
Fixes #702 

## Type of change

(Check the ones that apply by placing an "x" instead of the space in the [ ] so it becomes [x])

- [ ] Note merging this changes the node modules
- [ ] Note merging this changes the database configuration.
- [ ] This change requires a documentation update

## Checklist

(Note what you have done by placing an "x" instead of the space in the [ ] so it becomes [x]. It is hoped you do all of them.)

- [x ] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [ ] I have removed text in ( ) from the issue request

## Limitations

Issue should be fixed. I do not believe there is any further work to be done on this issue.

2022-04-22 22:04 UTC, huss commented
Hi @jbmayor4 and thank you for your PR. I don't see that you have signed our CLA. If you think you did then let me know. I did see a notice of a new signature but I did not see yours. We need a CLA to accept a contribution from someone. If you have questions then please let the project know.

2022-04-22 22:08 UTC, jbmayor4 commented
Hi @huss , I thought I signed the CLA, but in case I am wrong I have just resigned it. Let me know if there is anything else you need on my end.

2022-04-22 23:56 UTC, huss commented
Hi @jbmayor4. So, now I see both of your responses. It may have been a sync problem (or something I did wrong) but it clearly was not your issue as it shows you did it before and now. I appreciate your quick response. I'll try to work on this PR soon. Thank you for your first contribution.

2022-04-23 16:12 UTC, huss requested changes
Thanks to @jbmayor4 for addressing this issue. The code works fine. I have made a couple of (hopefully) quick change requests. We appreciate your first contribution.

2022-04-23 16:12 UTC, huss commented on src/client/app/translations/data.js
> +		"here": "here",
This is slightly off for where it should be alphabetically. It should be before "hide".

2022-04-23 16:12 UTC, huss commented on src/scripts/databaseBackup.sh
> +#!/bin/bash
This file does not relate to this PR but another one. I think it should be removed from this PR.

2022-05-08 22:21 UTC, huss commented
It has been about 2 weeks weeks since the PR review. I wanted to know if @jbmayor4  plans to make these changes or not. It is okay either way it would be nice to know so the project can continue to resolve this PR. There is also a merge conflict from new code on Tooltips that I can take care of once the other items are fixed up.

2022-05-23 18:12 UTC, huss commented on src/client/app/translations/data.js
> +		"here": "here",
I'm fixed this.

2022-05-23 18:14 UTC, huss commented on src/scripts/databaseBackup.sh
> +#!/bin/bash
I'm removing this file.

2022-05-23 18:37 UTC, huss approved these changes

2022-05-23 18:38 UTC, huss commented
Since the project did not hear from @jbmayor4 in two weeks, I have made the requested changes and resolved the merge conflict. The PR is now ready to merge.

2022-05-23 18:39 UTC, merged