Create migrations
OpenEnergyDashboard/OED pull request #761
Opened 2022-04-23 17:47 UTC by truongdd03

# Description

This PR creates migrations for new changes in the database.  The full update run by me failed so I marked this PR as a draft.

## Type of change

- [ ] Note merging this changes the node modules
- [ ] Note merging this changes the database configuration.
- [ ] This change requires a documentation update

## Checklist

- [x] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [x] I have removed text in ( ) from the issue request

## Limitations

2022-04-25 14:12 UTC, huss requested changes
Thanks to @truongdd03 for doing this. I've made a few suggested changes. I believe the migrations are now working for you so maybe this should not be draft anymore. Also, it might be good to note that this completes the resource generalization task "create DB migrations" in the description. Finally, I did a quick check and the migrations seem to work fine. I'll do a more extensive test with meter and group data after the changes are made.

2022-04-25 14:12 UTC, huss commented on src/server/migrations/0.8.0-1.0.0/sql/group/add_default_graphic_unit.sql
> +    ADD COLUMN IF NOT EXISTS default_graphic_unit INTEGER REFERENCES units(id) DEFAULT id_of_units('Electric_utility');
Two notes on this. First, I don't think we want to set the DEFAULT as this does not mirror the create_groups_table.sql. Instead, it should update the rows that exist in the groups table to use the desired default_graphic_unit after the alter to add that column. Second, I don't think current rows should be set to Electric_utility. This is the graphing unit and that cannot be a meter type. I think we want it to be kWh as OED assumed all graphics were that unit in the past.

2022-04-25 14:12 UTC, huss commented on src/server/migrations/0.8.0-1.0.0/sql/meter/add_default_units_and_conversions.sql
> +-- Insert Electric_utility, which is the unit for all existing meters/groups.
Per other comment, this is the unit of meters but not groups.

2022-04-25 14:12 UTC, huss commented on src/server/migrations/0.8.0-1.0.0/sql/meter/add_default_units_and_conversions.sql
> +CREATE OR REPLACE FUNCTION id_of_units(unit_name VARCHAR) RETURNS INTEGER AS $$
While using a function is an elegant solution, I have two thoughts. First, you use this in other migration files and that means that this must happen first. I think any such dependency should be carefully documented. Second, this leaves a function in the database that does not exist in unmigrated systems. I don't think that is a good idea. While it could be removed after migrations are done, I think it might be cleaner to select the needed id within the insert commands below and in other files to avoid the need for a function that is only used for migrations.

2022-04-25 14:12 UTC, huss commented on src/server/migrations/0.8.0-1.0.0/sql/meter/add_unit_id_default_graphic_unit.sql
> +-- Add unit_id and default_graphic_unit to the meters table.
As in the comment on groups, I don't think we should use DEFAULT but alter the current rows. In this case it is correct that it should be Electric_utility.

2022-04-25 14:12 UTC, huss commented on src/server/migrations/0.8.0-1.0.0/sql/meter/add_default_units_and_conversions.sql
> +INSERT INTO units(name, identifier, unit_represent, sec_in_rate, type_of_unit, unit_index, suffix, displayable, preferred_display, note)
The dependency that this must happen before other migrations (such as meters) should be documented here and in the index file.

2022-04-25 20:49 UTC, huss requested changes
I have not carefully tested this yet but noticed this one item while looking at the code.

2022-04-25 20:49 UTC, huss commented on src/server/migrations/0.8.0-1.0.0/sql/meter/add_default_units_and_conversions.sql
> +VALUES (id_of_units('Electric_utility'), id_of_units('kWh'), FALSE, 1, 0, 'Electric Utility → kWh')
This is still using the deleted function of id_of_units.

2022-04-25 23:31 UTC, truongdd03 commented
Thank you for your review, @huss. I have resolved all the comments. Please let me know if you think there is something else that needs to be changed. Thank you.

2022-04-27 17:23 UTC, huss approved these changes
Thanks to @truongdd03 for the quick changes. Everything seems good. I did a full migration from 0.8.0 and it worked. I have updated the help pages to reflect some changes in the process. This PR is ready to merge.

2022-04-27 17:24 UTC, merged