Units Page, (TODO Meters Page, Conversions Page), Select Component Dropdowns, (TODO New Graphic Rate Menu)
OpenEnergyDashboard/OED pull request #787
Opened 2022-07-24 21:50 UTC by Deelane

# Description

###Units Page

Overhauled the units page as introduced in PR 766, including additional functionality, bugfixes, and updates. The page is now complete and is being used as the template for the creation of similar pages like the Meters and Conversions pages. 

Notable changes are as follows:
- Components converted to hooks and now uses hooks to access and alter Redux store and local state.
- Container files removed.
- Actions optimized, unnecessary actions removed.
- State/Reducers optimized, unnecessary state removed.
- Fixed bugs with reducers not properly updating store state.
- Updated UI visuals.

###Meters Page (TODO)

Updated to match units page functionality and interface using units page as template.

###Conversions Page (TODO)

Created using units page as template.

###Select Component Dropdowns

Added functionality and fixed bugs associated with selecting groups, meters, and units from the dropdowns in the ChartDataSelectComponent. The component should now work as intended.

Notable changes are as follows:
- Added functions for determining compatibility for groups and meters with other selected items.
- Fixed bugs where store state was not properly updated.
- Fixed bugs associated with unselecting a unit.
- Select items are now properly disabled if they are incompatible with other items.
- Added functionality allowing for switching between units without clearing the unit.
- Clearing the selected unit now clears all meters and groups, resetting the graph.

###New Graphic Rate Menu (TODO)

Added a new rate menu allowing for changing of the time unit for line graphs.

###Issues Addressed

Partly Addresses #[726]
TODO Fixes #[644]

## Type of change

- [ ] Note merging this changes the node modules
- [ ] Note merging this changes the database configuration.
- [x] This change requires a documentation update

## Checklist

- [x] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [x] I have removed text in ( ) from the issue request

## Limitations

The TODOs must still be addressed.

2022-07-26 20:17 UTC, huss commented
I just pushed changes to the PR. See commit message/code changes for details.

I also note that the check is failing. All GitHub Action checks started failing recently so this is not an issue with this PR. I did run them locally and they all passed so I think the PR is okay.

My review should be posted soon.

2022-07-26 22:11 UTC, huss requested changes
Overall this works as expected. I did not look at the meter code yet since it was not done. I have left some comments to address. Thanks for the good work.

2022-07-26 22:11 UTC, huss commented on src/client/app/components/ChartDataSelectComponent.tsx
>  export function getUnitCompatibilityForDropdown(state: State) {
If this is only used in this file do we need to export?

2022-07-26 22:11 UTC, huss commented on src/client/app/components/ChartDataSelectComponent.tsx
> +		visibleUnitsOrSuffixes = _.filter(state.units.units, (o: UnitData) => {
I think it might be easier to check for DisplayableType.all and that would also be safer if another type is added.

2022-07-26 22:11 UTC, huss commented on src/client/app/components/RouteComponent.tsx
> +								{/* <Route path="/addUnit" render={() => this.requireAuth(<CreateUnitContainer />)}/> */}
Can this comment go?

2022-07-26 22:11 UTC, huss commented on src/client/app/components/unit/CreateUnitModalComponent.tsx
> +											required value={state.suffix} />
I'm uncertain what this required is for, esp. since you can save without entering any value.

2022-07-26 22:11 UTC, huss commented on src/client/app/components/unit/EditUnitModalComponent.tsx
> +// I realize that * is already imported from react
Can we get rid of the "I" and maybe give a reason for needing the second import?

2022-07-26 22:11 UTC, huss commented on src/client/app/components/unit/UnitViewComponent.tsx
> +// I realize that * is already imported from react
Same "I" comment as elsewhere.

2022-07-26 22:11 UTC, huss commented on src/client/app/components/unit/UnitViewComponent.tsx
> +				{/* <b><FormattedMessage id="unit.preferred.display" /></b> {props.unit.preferredDisplay.toString()} */}
Comment needed?

2022-07-26 22:11 UTC, huss commented on src/client/app/containers/ChartDataSelectContainer.ts
> +/* This Source Code Form is subject to the terms of the Mozilla Public
This file was brought back but I cannot see any use and I would think it is gone given the new Component with hooks. Is it needed? It also has overlapping functions with those in the ccomponent.

2022-07-26 22:11 UTC, huss commented on src/client/app/types/redux/actions.ts
> +	EditUnitDetails = 'EDIT_UNIT_DETAILS',
Is this used? I could not find it in a search.

2022-07-26 22:11 UTC, huss commented on src/client/app/types/redux/actions.ts
> +	DeleteEditedUnit = 'DELETE_EDITED_UNIT',
Is this used? I could not find it in a search.

2022-07-26 22:11 UTC, huss commented on src/client/app/types/redux/actions.ts
> +	EditMeterDetails = 'EDIT_METER_DETAILS',
Is this used? I could not find it in a search.

2022-07-26 22:11 UTC, huss commented on src/client/app/types/redux/actions.ts
> +	DeleteEditedMeter = 'DELETE_EDITED_METER',
Is this used? I could not find it in a search.

2022-07-26 22:11 UTC, huss commented on src/client/app/utils/api/unitsApi.ts
> +	public async details(): Promise<NamedIDItem[]> {
This seems very similar to getUnitsDetails. A search for unitsApi found a use of getUnitsDetails but not this one. Is it needed and what is it for?

2022-07-26 22:11 UTC, huss commented on src/server/routes/units.js
> +			id: {
id is not used as it must be set to undefined when adding to DB. I tried commenting this out and it does not matter. I know the value is sent because we send a unit) but would it be okay to remove it and put in a comment about why?

2022-07-26 22:11 UTC, huss commented on src/server/routes/units.js
> +			unitIndex: {
This is in the same category as id. The fact it may not be needed is seen from fact that number is mispelled.

2022-07-26 22:33 UTC, Deelane commented on src/client/app/components/unit/EditUnitModalComponent.tsx
> +// I realize that * is already imported from react
Removed the "I". The reason is purely visual for code readability. I can remove it if need be.

2022-07-26 22:34 UTC, Deelane commented on src/client/app/components/unit/UnitViewComponent.tsx
> +// I realize that * is already imported from react
Removed.

2022-07-26 22:35 UTC, Deelane commented on src/client/app/components/unit/UnitViewComponent.tsx
> +				{/* <b><FormattedMessage id="unit.preferred.display" /></b> {props.unit.preferredDisplay.toString()} */}
Comment not needed, removed.

2022-07-26 22:36 UTC, Deelane commented on src/client/app/components/ChartDataSelectComponent.tsx
>  export function getUnitCompatibilityForDropdown(state: State) {
Do not need to export, export removed.

2022-07-26 22:41 UTC, Deelane commented on src/client/app/components/ChartDataSelectComponent.tsx
> +		visibleUnitsOrSuffixes = _.filter(state.units.units, (o: UnitData) => {
Change made.

2022-07-26 22:42 UTC, Deelane commented on src/client/app/components/RouteComponent.tsx
> +								{/* <Route path="/addUnit" render={() => this.requireAuth(<CreateUnitContainer />)}/> */}
Comment gone.

2022-07-26 22:43 UTC, Deelane commented on src/client/app/containers/ChartDataSelectContainer.ts
> +/* This Source Code Form is subject to the terms of the Mozilla Public
File not needed, deleted it.

2022-07-26 22:47 UTC, Deelane commented on src/client/app/types/redux/actions.ts
> +	EditUnitDetails = 'EDIT_UNIT_DETAILS',
Not used, removed.

2022-07-26 22:49 UTC, Deelane commented on src/client/app/types/redux/actions.ts
> +	DeleteEditedUnit = 'DELETE_EDITED_UNIT',
Not used, removed.

2022-07-26 22:51 UTC, Deelane commented on src/client/app/utils/api/unitsApi.ts
> +	public async details(): Promise<NamedIDItem[]> {
Does not seem to be used. Removed.

2022-07-26 22:56 UTC, Deelane commented on src/server/routes/units.js
> +			unitIndex: {
Removed with no issues.

2022-07-26 23:02 UTC, Deelane commented on src/client/app/components/unit/CreateUnitModalComponent.tsx
> +											required value={state.suffix} />
I agree, it does nothing and was a remnant of the previous code. Removed all instances of required.

2022-07-27 16:27 UTC, huss commented
@wootent There are two comments on this PR that seem to involve code you added. They ask whether actions are needed since they don't seem to be used at this time. They are: EDIT_METER_DETAILS and DELETE_EDITED_METER. However, they might be used in upcoming work or I missed something. Could you let us know? Thanks.

2022-07-27 16:28 UTC, huss commented
The update by @Deelane covers everything involving them. The PR seems fine for units and the dropdown menus. It is on hold since it also has partly completed meter page work.

2022-07-28 04:26 UTC, wootent commented on src/client/app/types/redux/actions.ts
> +	DeleteEditedMeter = 'DELETE_EDITED_METER',
DeleteEditedMeter is the only action that is not currently in use, but I think its for future?

2022-07-28 18:40 UTC, huss commented
I just pushed changes for test data for rate meters and a comment on the extra action.

2022-07-31 17:23 UTC, huss approved these changes

2022-07-31 17:24 UTC, huss commented
The meter work is in PR #786 so merging this so others can easily incorporate.

2022-07-31 17:24 UTC, merged