Csv upload page for meters
OpenEnergyDashboard/OED pull request #822
Opened 2022-11-19 05:14 UTC by truongdd03

# Description

This PR brings in some changes:
- Convert unit and default graphic unit's ids into units on the CSV upload page for meters. It's now possible to import meters from CSV files.
- Refetch meter states when meters are uploaded via CSV files. Hence, users no longer need to refresh to see the changes.
- Bring some meter checks to the database (timezone, reading duplicates, and time sort).
- Add migrations for these new checks.

## Type of change

- [ ] Note merging this changes the node modules
- [x] Note merging this changes the database configuration.
- [x] This change requires a documentation update

## Checklist

- [x] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [x] I have removed text in ( ) from the issue request

## Limitations

2022-11-20 20:27 UTC, huss commented
I have pushed two changes:

1. Change error message so clearer. This was noticed during testing but not something that @truongdd03 should have done.
2. Merged development since I had issues with login that are likely due to my changes in clearing a recent PR.

2022-11-20 20:29 UTC, huss requested changes
Thanks to @truongdd03 for carefully dealing with this change for units on the CSV page. I have made a couple of comments to address. I tried to do extensive testing of loading good meters, bad meters, multiple meter in a file and using curl. No issues were found. This can be merged once the small comments are addressed.

2022-11-20 20:29 UTC, huss commented on src/client/app/components/meters/EditMeterModalComponent.tsx
I think the checks for area and duplication should be put back. The message from the DB is okay for duplication but the one for area is not clear. That message is "Failed to edit meter with message: "validation failed with instance.area is not exactly one from [subschema 0],[subschema 1]"" The original checks were very clear. I also think it is better to warn here before the routing in these cases because with the DB you only see one of multiple ones possible. Finally, if any change is made then create should mirror these (they do not now since those were unchanged).

2022-11-20 20:29 UTC, huss commented on src/server/migrations/0.8.0-1.0.0/sql/meter/add_constraints.sql
> +ALTER TABLE meters ADD CONSTRAINT time_sort CHECK (time_sort::TEXT = 'increasing' OR time_sort::TEXT = 'decreasing');
I think this also need the area check as done in create_meters_table.sql.

2022-11-21 02:05 UTC, truongdd03 commented on src/client/app/components/meters/EditMeterModalComponent.tsx
I got it and brought these checks back.

2022-11-21 02:05 UTC, truongdd03 commented on src/server/migrations/0.8.0-1.0.0/sql/meter/add_constraints.sql
> +ALTER TABLE meters ADD CONSTRAINT time_sort CHECK (time_sort::TEXT = 'increasing' OR time_sort::TEXT = 'decreasing');
I added in the latest commit.

2022-11-21 02:06 UTC, truongdd03 commented
Thank you for the review, @huss. I have resolved all the comments. Please let me know if you find something that's needed to be changed. Thanks!

2022-11-21 03:04 UTC, huss commented
Thanks to @truongdd03 for the quick edits. Everything looks good.

2022-11-21 03:04 UTC, huss approved these changes

2022-11-21 03:04 UTC, merged