change meter/group selection logic and dropdown sorting
OpenEnergyDashboard/OED pull request #825
Opened 2022-11-28 14:02 UTC by spearec

# Description

This PR changes the logic for determining when a meter/group is selected or deselected and changes the sorting for the dropdown menus. The new sorting has a divider to clearly show the user why incompatible meters are greyed out, as well as putting meters without GPS below those with GPS in the map view while preserving the original order.

![image](https://user-images.githubusercontent.com/113216142/204296522-3346a3c2-d8dd-42a3-a75b-f6f1ab42ee21.png)

Fixes #600 

## Type of change

- [ ] Note merging this changes the node modules
- [ ] Note merging this changes the database configuration.
- [ ] This change requires a documentation update

## Checklist

- [x] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [x] I have removed text in ( ) from the issue request

2022-11-28 17:25 UTC, huss requested changes
Thanks to @spearec for more good work. I like the separators on the menus and the consistent use. I have a couple of comments on commenting but nothing else. Testing indicates it works as expected.

2022-11-28 17:25 UTC, huss commented on src/client/app/components/ChartDataSelectComponent.tsx
> +					// change logic for selection: compute diff between dataProps.selectedMeters and newSelectedMeterOptions\
Remove \ at end of comment?

2022-11-28 17:25 UTC, huss commented on src/client/app/components/ChartDataSelectComponent.tsx
> +						const allSelectedGroupIDs: number[] = dataProps.allSelectedGroups.map(s => s.value);
There are more comments in the section below but even with these I think some more would help future developers. Could you describe why each of the filters work and any other choices?

2022-11-29 14:19 UTC, spearec commented
I've added some more comments and changed variable names to be consistent with term usage. This makes the distinction between displayable items (an admin-level setting) and compatible items (determined by graph type/unit selection).

2022-11-29 21:33 UTC, huss approved these changes

2022-11-29 21:33 UTC, huss commented
Everything looks good. Thanks.

2022-11-29 21:34 UTC, merged