types: Miscellaneous improvements
OpenEnergyDashboard/OED pull request #861
Opened 2023-02-18 03:42 UTC by hyperupcall

# Description

These changes improve typings in two areas:
1. Correctly specifying the return type of the `failure` function (`||` an operator in TypeScript)
2. Fixing type inference for `express.*` types (lines 8-9) by importing `express`
  2a. This could also be fixed by using the global `Express` type, but this was avoided for consistency

## Type of change

- [] Note merging this changes the node modules
- [] Note merging this changes the database configuration.
- [] This change requires a documentation update

## Checklist

- [x] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [x] I have removed text in ( ) from the issue request

## Limitations

N/A

2023-02-19 20:51 UTC, huss commented on src/server/services/csvPipeline/success.js
> +const express = require('express')
I think (guess) it is okay to add a require for the comment. However, if we are going to do that then I would also do it in failure.js as it seems to be the same usage there.

One final thought is to put a comment on the require to indicate it is needed to resolve the type in the comment so it is clear for future developers.

2023-02-19 20:52 UTC, huss requested changes
Thanks to @huperupcall for another PR. This seems fine and I just made what I hope is a simple comment to resolve.

2023-02-19 21:02 UTC, hyperupcall commented
made those changes :+1:

2023-02-20 02:31 UTC, huss approved these changes

2023-02-20 02:31 UTC, huss commented
Thanks to @hyperupcall for the quick changes. Everything looks good and this is ready to merge.

2023-02-20 02:32 UTC, merged