Add 10 unit tests to readings.js
OpenEnergyDashboard/OED pull request #864
Opened 2023-02-18 19:45 UTC by ZhenyuYu1

# Description

This pull request adds 10 unit tests to readings.js based on the requirements from the [testing docs](https://github.com/OpenEnergyDashboard/DesignDocs/blob/main/testing/testing.md). 

- should have daily points for 15 minute reading intervals and flow units with +-inf start/end time & kW as kW
- 15 days barely gives hourly points & middle readings
- 14 days barely gives raw points & middle readings
- should have daily points for 15 minute reading intervals and quantity units with +-inf start/end time & kWh as MJ
- should have daily points for 15 minute reading intervals and quantity units with +-inf start/end time & kWh as MJ reverse conversion
- should have daily points for 15 minute reading intervals and quantity units with +-inf start/end time & kWh as BTU chained
- should have hourly points for middle readings of 15 minute for a 60 day period and quantity units & kWh as MJ
- should have hourly points for middle readings of 15 minute for a 60 day period and raw units & C as F with intercept
- should have raW points for middle readings of 15 minute for a 14 day period and quantity units & kWh as MJ
- should have raw points for middle readings of 15 minute for a 14 day period and raw units & C as F with intercept
- should have daily points for 15 minute reading intervals and flow units with +-inf start/end time & thing as thing where rate is 36

Fixes #862

## Type of change
- [ ] Note merging this changes the node modules
- [ ] Note merging this changes the database configuration.
- [ ] This change requires a documentation update

## Checklist

- [x] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [x] I have removed text in ( ) from the issue request

## Limitations

2023-02-18 19:49 UTC, ZhenyuYu1 commented
We worked off of development branch on our fork, but then read the guidelines and made a branch off of that to merge in. If that is an issue we can delete our commits off of dev branch on our fork.

2023-02-18 19:53 UTC, huss commented
> We worked off of development branch on our fork, but then read the guidelines and made a branch off of that to merge in. If that is an issue we can delete our commits off of dev branch on our fork.

This should be fine. The issue is that if you do all your work off a branch then if you continue working/committing/pushing to that branch then it changes the PR. So, having separate branches allows for a developer to continue new work after a PR and before it is merged. The development branch on your own fork is not an issue except be aware that if you branch from it then it cannot be merged into OED until this PR is approved since it contains that work,

2023-02-19 21:32 UTC, huss commented
Thanks to @iansw246 and @ZhenyuYu1 for their first PR. OED appreciates your contribution. From the records I see, neither of you have agreed to the [OED CLA](https://openenergydashboard.github.io/developer/cla.html). The project needs that before we can accept your contribution. Please let me know if you have any questions or if you think I missed your CLA. @AaronHamilton965 has a CLA record. Thanks.

2023-02-19 22:31 UTC, huss requested changes
Thank you for your first PR. I tried to carefully check all the added tests and everything seemed okay. I did make one comment that should be addressed and another to fix my own typo.

Just for the record, a few of the new data files are not yet used in any test. I think that is fine as they should be soon with more tests added.

I have updated the designDoc to reflect the tests done in the PR.

2023-02-19 22:31 UTC, huss commented on src/server/test/web/readings.js
> +				mocha.it('should have daily points for 15 minute reading intervals and flow units with +-inf start/end time & kW as kW', async () => {
I think this test was already implmented (See starting line 273). That is why the design table indicated it was done.

2023-02-19 22:31 UTC, huss commented on src/server/test/web/readings.js
> +				mocha.it('should have raW points for middle readings of 15 minute for a 14 day period and quantity units & kWh as MJ', async () => {
Would you be willing to fix my typo so raW -> raw?

2023-02-19 23:40 UTC, huss commented
The changes look fine. Thank you for doing them so quickly. This PR can be merged (and approved) once the final CLA is in place.

2023-02-20 02:18 UTC, huss approved these changes

2023-02-20 02:19 UTC, huss commented
Thanks to @ZhenyuYu1 and @iansw246 for working on this so quickly. It is great and ready to merge.

2023-02-20 02:19 UTC, merged