Use jsdoc rules recommended for typescript
OpenEnergyDashboard/OED pull request #956
Opened 2023-06-23 17:36 UTC by spearec

# Description

Merging #949 caused a few issues with jsdoc, and while resolving those I had a look through the package documentation. There is a specific recommended ruleset for typescript, which is different from what OED was using. This ruleset removes the need for types in jsdoc headers, as they are redundant since typescript is a typed language.
I also took the chance to use eslint overrides to disable jsdoc as a rule for actions, reducers, and containers, instead of disabling jsdoc on a per-file basis. This allows easier control over the rules for these files as a group.

## Type of change

(Check the ones that apply by placing an "x" instead of the space in the [ ] so it becomes [x])

- [ ] Note merging this changes the database configuration.
- [ ] This change requires a documentation update

## Checklist

- [x] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [x] I have removed text in ( ) from the issue request

2023-06-25 17:05 UTC, huss requested changes
Thanks to @spearec for quickly updating the files based on the recent update to eslint. I know removing all those recent edits was painful so I am esp. grateful.

I've made a couple of comments but overall this looks very good. Note I added a comment in issue #726 so the TODOs in .eslintrc.json will be addressed.

2023-06-25 17:05 UTC, huss commented on src/client/app/actions/admin.ts
>  /* eslint-enable */
Should this enable be removed since I think the disable above was?

2023-06-25 17:05 UTC, huss commented on src/client/app/containers/maps/MapCalibrationChartDisplayContainer.ts
>  /* eslint-enable */
Should this enable be removed since disable above was?

2023-06-25 17:05 UTC, huss commented on src/client/app/utils/api/ReadingsApi.ts
> +	 * @returns LineReadings in sorted order
Should this be BarReadings?

2023-06-25 17:05 UTC, huss commented on src/client/app/utils/calculateCompare.ts
> + * @returns human-readable names for the compare period
Would it make sense at the end to add:
as {{prev: string, current: string}}
so the person knows the format?

2023-06-25 17:05 UTC, huss commented on src/client/app/utils/calculateCompare.ts
> + * @param labels the names of the periods in question
Same as ... if make change above.

2023-06-25 17:05 UTC, huss commented on src/client/app/utils/graphics.ts
> + * @returns y-axis label and boolean of whether rate needs to be scaled (true if does)
As other comments, return the JSON structure if we are doing that.

2023-06-26 12:43 UTC, spearec commented
> As other comments, return the JSON structure if we are doing that. 

In this case, the JSON structure is directly noted in the function header instead of an interface, so the mouseover text of the function has the structure.

2023-06-26 13:18 UTC, huss approved these changes

2023-06-26 13:18 UTC, merged