Solved #947 by updating the usage of cookie-parser dependencies
OpenEnergyDashboard/OED pull request #987
Opened 2023-08-08 05:51 UTC by moll0928

# Description
 Solved #947 by updating the usage of cookie-parser dependencies, by testing, we found out the website does not need the cookie-parser dependency, so we decided to directly delete it.

Fixes #[947]

(In general, OED likes to have at least one issue associated with each pull request. Replace [issue] with the OED GitHub issue number. In the preview you will see an issue description if you hover over that number. You can create one yourself before doing this pull request. This is where details are normally given on what is being addressed. Note you should not use the word "Fixes" if it does not completely address the issue since the issue would automatically be closed on merging the pull request. In that case use "Partly Addresses #[issue].)

## Type of change

(Check the ones that apply by placing an "x" instead of the space in the [ ] so it becomes [x])

- [x] Note merging this changes the database configuration.
- [x] This change requires a documentation update

## Checklist

(Note what you have done by placing an "x" instead of the space in the [ ] so it becomes [x]. It is hoped you do all of them.)

- [x] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [x] I have removed text in ( ) from the issue request

## Limitations

(Describe any issues that remain or work that should still be done.)

2023-08-08 05:58 UTC, moll0928 reviewed
Solved the problem #947, by testing its usage and finding out that the website does not need this dependency. Thus we decided to delete this redundant dependency and kept the work efficiency of the website.

2023-08-16 04:20 UTC, moll0928 commented
Done with @1jc

2023-08-16 04:22 UTC, salhernandez commented
@huss this PR is ready for Code Review

2023-08-17 23:38 UTC, huss requested changes
Thanks to @Moll0928 for their first pull request to OED. A few  items to address are:

- You removed cookie-parser from package.json. It is still present in package-lock.json. The easiest way to fix this is to put it back into package.json and then open a shell in the OED web container (see developer getting started) and run the following command:
``` npm uninstall cookie-parser```
This should avoid any other unneeded changes to these files that would happen from an npm update.
- You edited the pull_request_template.md file but it should not be changed. When you open a pull request to OED it will show this in the create window. You then make changes in that window. That will only effect what is shown in your pull request rather than changing future pull requests which is what happens if you edit the file.
- From my records, I do not see you having signed the Contributor License Agreement for OED. The directions for doing this are on the developer help page. If I am mistaken about your having signed the CLA then please let me know.

2023-08-18 01:53 UTC, moll0928 commented
@huss Hi huss, I got the review above, do you recommend to have a new PR or directly modify this PR. I just tried to modify this one but its is kind of hard for me. So what I want to do is have a new PR and close this one, is it fine to you?

2023-08-18 02:03 UTC, salhernandez commented
@moll0928 you can delete the commit where you update the pull request template by doing an interactive rebase.

You can use this as a reference: https://gist.github.com/todgru/5158779

2023-08-18 02:04 UTC, huss commented
> @huss Hi huss, I got the review above, do you recommend to have a new PR or directly modify this PR. I just tried to modify this one but its is kind of hard for me. So what I want to do is have a new PR and close this one, is it fine to you?

If you prefer to do a new PR then that is fine. I can close the old one when that is submitted.

2023-08-21 06:59 UTC, closed without merging